/* ==============================================================
 *  FILE:    activity.c
 *  ROLE:    任务循环体实现（Task Job Implementations）
 *
 *  IMA 架构层次：线程层（Thread Layer）
 *  IMA 分区：ps5 (P5)     模块：M2 (arinckernel.module2)
 *  对应 AADL 文件：DIMA_threads.aadl
 *    AADL thread Tsk51/Tsk52/Tsk53 各自对应一个周期性任务。
 *
 *  本文件是 ps5 分区的核心执行代码，实现各任务的 while(1) 主循环。
 *  每个任务的执行流程为：
 *    1. 调用 ARINC 653 APEX 服务收发消息（RECEIVE/SEND）
 *    2. （可选）调用用户计算函数
 *    3. 调用 PERIODIC_WAIT() 挂起，等待下一个调度周期
 *
 *  ps5 分区特点：
 *    - task51：只读 order_in 队列端口
 *    - task52：读 order_in → 处理 → 写 queueingout（消息转发节点）
 *    - task53：无任何端口操作（纯计算占位任务）
 *    - 无分区内通信（无黑板、无缓冲区）
 * ==============================================================*/

#include <os/pos/apex/apexLib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ps5  AADL: P5.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


#define SZ 1024

/* ================================================================== */
/*  task51  (AADL: Tsk51)
 *  Period=50ms  Priority=1  Dispatch_Abs=0ms
 *  Inter-partition READS:  order_in (QUEUING DEST)
 * ================================================================== */
extern QUEUING_PORT_ID_TYPE ps5_order_in_id;

void* task51_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* RECEIVE inter-partition QUEUING: order_in */
        RECEIVE_QUEUING_MESSAGE(ps5_order_in_id,
            5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(order_in)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task51)", ret);
    }
}

/* ================================================================== */
/*  task52  (AADL: Tsk52)
 *  Period=50ms  Priority=2  Dispatch_Abs=2ms
 *  Inter-partition WRITES: queueingout (QUEUING SOURCE)
 *  Inter-partition READS:  order_in (QUEUING DEST)
 * ================================================================== */
extern QUEUING_PORT_ID_TYPE ps5_order_in_id;
extern QUEUING_PORT_ID_TYPE ps5_queueingout_id;

void* task52_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* RECEIVE inter-partition QUEUING: order_in */
        RECEIVE_QUEUING_MESSAGE(ps5_order_in_id,
            5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(order_in)", ret);

        /* SEND inter-partition QUEUING: queueingout */
        SEND_QUEUING_MESSAGE(ps5_queueingout_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer),
            5000000ll, &ret);
        CHECK_CODE("SEND_QUEUING_MESSAGE(queueingout)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task52)", ret);
    }
}

/* ================================================================== */
/*  task53  (AADL: Tsk53)
 *  Period=200ms  Priority=3  Dispatch_Abs=0ms
 * ================================================================== */

void* task53_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task53)", ret);
    }
}

