#include <os/pos/apex/apexLib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ps5  AADL: P5.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


#define SZ 1024

/* ================================================================== */
/*  task51  (AADL: Tsk51)
 *  Period=50ms  Priority=1  Dispatch_Abs=0ms
 *  Inter-partition READS:  order_in (QUEUING DEST)
 * ================================================================== */
extern QUEUING_PORT_ID_TYPE ps5_order_in_id;

void* task51_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* RECEIVE inter-partition QUEUING: order_in */
        RECEIVE_QUEUING_MESSAGE(ps5_order_in_id,
            5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(order_in)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task51)", ret);
    }
}

/* ================================================================== */
/*  task52  (AADL: Tsk52)
 *  Period=50ms  Priority=2  Dispatch_Abs=2ms
 *  Inter-partition WRITES: queueingout (QUEUING SOURCE)
 *  Inter-partition READS:  order_in (QUEUING DEST)
 * ================================================================== */
extern QUEUING_PORT_ID_TYPE ps5_order_in_id;
extern QUEUING_PORT_ID_TYPE ps5_queueingout_id;

void* task52_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* RECEIVE inter-partition QUEUING: order_in */
        RECEIVE_QUEUING_MESSAGE(ps5_order_in_id,
            5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(order_in)", ret);

        /* SEND inter-partition QUEUING: queueingout */
        SEND_QUEUING_MESSAGE(ps5_queueingout_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer),
            5000000ll, &ret);
        CHECK_CODE("SEND_QUEUING_MESSAGE(queueingout)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task52)", ret);
    }
}

/* ================================================================== */
/*  task53  (AADL: Tsk53)
 *  Period=200ms  Priority=3  Dispatch_Abs=0ms
 * ================================================================== */

void* task53_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task53)", ret);
    }
}

