#ifndef __PS5_GENERATED_ACTIVITY_H_
#define __PS5_GENERATED_ACTIVITY_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ps5  AADL: P5.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

/* Periodic task: task51 (AADL: Tsk51)
 * Period=50ms  Priority=1  Stack=8192B */
void* task51_job(void);

/* Periodic task: task52 (AADL: Tsk52)
 * Period=50ms  Priority=2  Stack=8192B */
void* task52_job(void);

/* Periodic task: task53 (AADL: Tsk53)
 * Period=200ms  Priority=3  Stack=8192B */
void* task53_job(void);

#endif
