#ifndef __PS5_GENERATED_GTYPES_H_
#define __PS5_GENERATED_GTYPES_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ps5  AADL: P5.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

#include <os/pos/apex/apexLib.h>

typedef int integer;

#endif
