/* ==============================================================
 *  FILE:    main.c
 *  ROLE:    分区入口与资源初始化（Partition Entry & Resource Init）
 *
 *  IMA 架构层次：分区层（Partition Layer）
 *  IMA 分区：ps5 (P5)     模块：M2 (arinckernel.module2)
 *  对应 AADL 文件：
 *    - DIMA_partitions.aadl ：分区定义（端口、资源声明）
 *    - DIMA_models.aadl     ：分区绑定到处理器模块
 *    - DIMA_threads.aadl    ：线程（任务）属性（周期、优先级等）
 *
 *  appMain() 是 ARINC 653 操作系统启动后调用的分区入口函数。
 *  它只执行一次，负责创建分区所需的全部资源，然后切换到 NORMAL 模式。
 *
 *  执行步骤：
 *    1. CREATE_QUEUING_PORT / CREATE_SAMPLING_PORT — 创建分区间通信端口
 *       对应 AADL: partition 的 feature（in/out data port / event data port）
 *    2. CREATE_BLACKBOARD / CREATE_BUFFER          — 创建分区内通信资源
 *       对应 AADL: thread 之间的 data access 连接
 *    3. CREATE_PROCESS + START                     — 创建并启动各任务
 *       对应 AADL: thread 及其 Period、Priority 属性
 *    4. SET_PARTITION_MODE(NORMAL)                 — 切换到正常运行模式
 *       此后 appMain 返回，RTOS 开始周期调度各任务
 * ==============================================================*/
#include <os/pos/apex/apexLib.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ps5  AADL: P5.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


PROCESS_ID_TYPE arinc_threads[ACoreOS653_CONFIG_NB_THREADS];

/* ---- Inter-partition ports ---- */
QUEUING_PORT_ID_TYPE  ps5_queueingout_id;
QUEUING_PORT_ID_TYPE  ps5_order_in_id;

void appMain(void)
{
    PROCESS_ATTRIBUTE_TYPE tattr;
    RETURN_CODE_TYPE ret = NO_ERROR;

    /* 1. Task: task51 (AADL: Tsk51)  Period=50ms Priority=1 */
    strcpy(tattr.NAME, "task51");
    tattr.ENTRY_POINT   = task51_job;
    tattr.BASE_PRIORITY = 1;
    tattr.PERIOD        = 50000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 50000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[0]), &ret);
    CHECK_CODE("CREATE_PROCESS(task51)", ret);
    START(arinc_threads[0], &ret);
    CHECK_CODE("START(task51)", ret);

    /* 2. Task: task52 (AADL: Tsk52)  Period=50ms Priority=2 */
    strcpy(tattr.NAME, "task52");
    tattr.ENTRY_POINT   = task52_job;
    tattr.BASE_PRIORITY = 2;
    tattr.PERIOD        = 50000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 50000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[1]), &ret);
    CHECK_CODE("CREATE_PROCESS(task52)", ret);
    START(arinc_threads[1], &ret);
    CHECK_CODE("START(task52)", ret);

    /* 3. Task: task53 (AADL: Tsk53)  Period=200ms Priority=3 */
    strcpy(tattr.NAME, "task53");
    tattr.ENTRY_POINT   = task53_job;
    tattr.BASE_PRIORITY = 3;
    tattr.PERIOD        = 200000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 50000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[2]), &ret);
    CHECK_CODE("CREATE_PROCESS(task53)", ret);
    START(arinc_threads[2], &ret);
    CHECK_CODE("START(task53)", ret);

    /* 4. Queuing port: queueingout (SOURCE) */
    CREATE_QUEUING_PORT(
        "queueingout",
        sizeof(integer),
        4,
        SOURCE,
        FIFO,
        &(ps5_queueingout_id), &ret);
    CHECK_CODE("CREATE_QUEUING_PORT(queueingout)", ret);

    /* 5. Queuing port: order_in (DESTINATION) */
    CREATE_QUEUING_PORT(
        "order_in",
        sizeof(integer),
        10,
        DESTINATION,
        FIFO,
        &(ps5_order_in_id), &ret);
    CHECK_CODE("CREATE_QUEUING_PORT(order_in)", ret);

    /* 6. Switch to NORMAL operating mode */
    SET_PARTITION_MODE(NORMAL, &ret);
    CHECK_CODE("SET_PARTITION_MODE(NORMAL)", ret);
    return;
}

/* ==============================================================
 *  健康监控回调函数（Health Monitoring Callbacks）
 *
 *  ARINC 653 HM 机制：当操作系统检测到错误（内存越界、时间超限等），
 *  会调用对应的回调函数，由应用决定如何处置（记录日志、重启分区等）。
 *
 *  module.xml 中的绑定：
 *    Module_HM_Table    ModuleCallback="module_HM_callback"
 *    Partition_HM_Table PartitionCallback="partition_HM_callback"
 * ==============================================================*/

/* 模块级 HM 回调：模块初始化阶段或系统功能执行阶段发生错误时调用 */
void module_HM_callback(ERROR_STATUS_TYPE *error_status)
{
    printf("[HM MODULE ps5 (P5)] ErrorID=%d  FailedProcess=%d  State=%d\n",
           (int)error_status->ERROR_IDENTIFIER,
           (int)error_status->FAILED_PROCESS_ID,
           (int)error_status->SYSTEM_STATE);
    /* TODO: 根据 ErrorID 决定具体处置策略（记录日志、触发 SHUTDOWN 等）*/
}

/* 分区级 HM 回调：分区初始化或运行阶段发生错误时调用 */
void partition_HM_callback(ERROR_STATUS_TYPE *error_status)
{
    printf("[HM PARTITION ps5 (P5)] ErrorID=%d  FailedProcess=%d\n",
           (int)error_status->ERROR_IDENTIFIER,
           (int)error_status->FAILED_PROCESS_ID);
    /* TODO: 根据 ErrorID 决定处置策略（IDLE / COLD_START / WARM_START 等）*/
}
