#include <os/pos/apex/apexLib.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ps5  AADL: P5.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


PROCESS_ID_TYPE arinc_threads[ACoreOS653_CONFIG_NB_THREADS];

/* ---- Inter-partition ports ---- */
QUEUING_PORT_ID_TYPE  ps5_queueingout_id;
QUEUING_PORT_ID_TYPE  ps5_order_in_id;

void appMain(void)
{
    PROCESS_ATTRIBUTE_TYPE tattr;
    RETURN_CODE_TYPE ret = NO_ERROR;

    /* 1. Task: task51 (AADL: Tsk51)  Period=50ms Priority=1 */
    strcpy(tattr.NAME, "task51");
    tattr.ENTRY_POINT   = task51_job;
    tattr.BASE_PRIORITY = 1;
    tattr.PERIOD        = 50000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 50000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[0]), &ret);
    CHECK_CODE("CREATE_PROCESS(task51)", ret);
    START(arinc_threads[0], &ret);
    CHECK_CODE("START(task51)", ret);

    /* 2. Task: task52 (AADL: Tsk52)  Period=50ms Priority=2 */
    strcpy(tattr.NAME, "task52");
    tattr.ENTRY_POINT   = task52_job;
    tattr.BASE_PRIORITY = 2;
    tattr.PERIOD        = 50000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 50000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[1]), &ret);
    CHECK_CODE("CREATE_PROCESS(task52)", ret);
    START(arinc_threads[1], &ret);
    CHECK_CODE("START(task52)", ret);

    /* 3. Task: task53 (AADL: Tsk53)  Period=200ms Priority=3 */
    strcpy(tattr.NAME, "task53");
    tattr.ENTRY_POINT   = task53_job;
    tattr.BASE_PRIORITY = 3;
    tattr.PERIOD        = 200000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 50000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[2]), &ret);
    CHECK_CODE("CREATE_PROCESS(task53)", ret);
    START(arinc_threads[2], &ret);
    CHECK_CODE("START(task53)", ret);

    /* 4. Queuing port: queueingout (SOURCE) */
    CREATE_QUEUING_PORT(
        "queueingout",
        sizeof(integer),
        4,
        SOURCE,
        FIFO,
        &(ps5_queueingout_id), &ret);
    CHECK_CODE("CREATE_QUEUING_PORT(queueingout)", ret);

    /* 5. Queuing port: order_in (DESTINATION) */
    CREATE_QUEUING_PORT(
        "order_in",
        sizeof(integer),
        10,
        DESTINATION,
        FIFO,
        &(ps5_order_in_id), &ret);
    CHECK_CODE("CREATE_QUEUING_PORT(order_in)", ret);

    /* 6. Switch to NORMAL operating mode */
    SET_PARTITION_MODE(NORMAL, &ret);
    CHECK_CODE("SET_PARTITION_MODE(NORMAL)", ret);
    return;
}
