#include <os/pos/apex/apexLib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: pc  AADL: PC.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


#define SZ 1024

/* ================================================================== */
/*  taskC1  (AADL: TskC1)
 *  Period=25ms  Priority=2  Dispatch_Abs=0ms
 *  Inter-partition READS:  data_in (SAMPLING DEST)
 *  Intra-partition WRITES (BB):  bb_data_link
 *  Intra-partition WRITES (BUF): buf_msg_queue
 * ================================================================== */
extern BLACKBOARD_ID_TYPE pc_bb_data_link_id;
extern BUFFER_ID_TYPE pc_buf_msg_queue_id;
extern SAMPLING_PORT_ID_TYPE pc_data_in_id;

void* taskC1_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    VALIDITY_TYPE    validity;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* READ inter-partition SAMPLING: data_in */
        READ_SAMPLING_MESSAGE(pc_data_in_id,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &validity, &ret);
        CHECK_VALIDCODE("READ_SAMPLING_MESSAGE(data_in)", validity, ret);

        /* DISPLAY intra-partition BLACKBOARD: bb_data_link */
        DISPLAY_BLACKBOARD(pc_bb_data_link_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer), &ret);
        CHECK_CODE("DISPLAY_BLACKBOARD(bb_data_link)", ret);

        /* WRITE intra-partition BUFFER: buf_msg_queue */
        WRITE_BUFFER(pc_buf_msg_queue_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer),
            5000000ll, &ret);
        CHECK_CODE("WRITE_BUFFER(buf_msg_queue)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(taskC1)", ret);
    }
}

/* ================================================================== */
/*  taskC2  (AADL: TskC2)
 *  Period=50ms  Priority=3  Dispatch_Abs=0ms
 *  Inter-partition READS:  data_in (SAMPLING DEST)
 *  Intra-partition READS  (BB):  bb_data_link
 *  Intra-partition READS  (BUF): buf_msg_queue
 * ================================================================== */
extern BLACKBOARD_ID_TYPE pc_bb_data_link_id;
extern BUFFER_ID_TYPE pc_buf_msg_queue_id;
extern SAMPLING_PORT_ID_TYPE pc_data_in_id;

void* taskC2_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    VALIDITY_TYPE    validity;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* READ inter-partition SAMPLING: data_in */
        READ_SAMPLING_MESSAGE(pc_data_in_id,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &validity, &ret);
        CHECK_VALIDCODE("READ_SAMPLING_MESSAGE(data_in)", validity, ret);

        /* READ intra-partition BLACKBOARD: bb_data_link */
        READ_BLACKBOARD(pc_bb_data_link_id, 0ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("READ_BLACKBOARD(bb_data_link)", ret);

        /* READ intra-partition BUFFER: buf_msg_queue */
        READ_BUFFER(pc_buf_msg_queue_id, 5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("READ_BUFFER(buf_msg_queue)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(taskC2)", ret);
    }
}

/* ================================================================== */
/*  taskC3  (AADL: TskC3)
 *  Period=100ms  Priority=4  Dispatch_Abs=0ms
 *  Inter-partition READS:  data_in (SAMPLING DEST)
 *  Inter-partition WRITES: cmd_out (QUEUING SOURCE)
 * ================================================================== */
extern QUEUING_PORT_ID_TYPE pc_cmd_out_id;
extern SAMPLING_PORT_ID_TYPE pc_data_in_id;

void* taskC3_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    VALIDITY_TYPE    validity;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* READ inter-partition SAMPLING: data_in */
        READ_SAMPLING_MESSAGE(pc_data_in_id,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &validity, &ret);
        CHECK_VALIDCODE("READ_SAMPLING_MESSAGE(data_in)", validity, ret);

        /* SEND inter-partition QUEUING: cmd_out */
        SEND_QUEUING_MESSAGE(pc_cmd_out_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer),
            5000000ll, &ret);
        CHECK_CODE("SEND_QUEUING_MESSAGE(cmd_out)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(taskC3)", ret);
    }
}

