#ifndef __PC_GENERATED_ACTIVITY_H_
#define __PC_GENERATED_ACTIVITY_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: pc  AADL: PC.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

/* Periodic task: taskC1 (AADL: TskC1)
 * Period=25ms  Priority=2  Stack=8192B */
void* taskC1_job(void);

/* Periodic task: taskC2 (AADL: TskC2)
 * Period=50ms  Priority=3  Stack=8192B */
void* taskC2_job(void);

/* Periodic task: taskC3 (AADL: TskC3)
 * Period=100ms  Priority=4  Stack=8192B */
void* taskC3_job(void);

#endif
