#include <os/pos/apex/apexLib.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: pc  AADL: PC.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


PROCESS_ID_TYPE arinc_threads[ACoreOS653_CONFIG_NB_THREADS];

/* ---- Inter-partition ports ---- */
SAMPLING_PORT_ID_TYPE pc_data_in_id;
QUEUING_PORT_ID_TYPE  pc_cmd_out_id;

/* ---- Intra-partition blackboards ---- */
BLACKBOARD_ID_TYPE pc_bb_data_link_id;  /* taskC1 -> taskC2 */

/* ---- Intra-partition buffers ---- */
BUFFER_ID_TYPE pc_buf_msg_queue_id;  /* taskC1 -> taskC2 */

void appMain(void)
{
    PROCESS_ATTRIBUTE_TYPE tattr;
    RETURN_CODE_TYPE ret = NO_ERROR;

    /* 1. Sampling port: data_in (DESTINATION) */
    CREATE_SAMPLING_PORT(
        "data_in",
        sizeof(integer),
        DESTINATION,
        100ll,
        &(pc_data_in_id), &ret);
    CHECK_CODE("CREATE_SAMPLING_PORT(data_in)", ret);

    /* 2. Blackboard: bb_data_link  (taskC1 -> taskC2) */
    CREATE_BLACKBOARD(
        "bb_data_link",
        sizeof(integer),
        &(pc_bb_data_link_id), &ret);
    CHECK_CODE("CREATE_BLACKBOARD(bb_data_link)", ret);

    /* 3. Buffer: buf_msg_queue  (taskC1 -> taskC2) */
    CREATE_BUFFER(
        "buf_msg_queue",
        sizeof(integer),
        4,
        FIFO,
        &(pc_buf_msg_queue_id), &ret);
    CHECK_CODE("CREATE_BUFFER(buf_msg_queue)", ret);

    /* 4. Task: taskC1 (AADL: TskC1)  Period=25ms Priority=2 */
    strcpy(tattr.NAME, "taskC1");
    tattr.ENTRY_POINT   = taskC1_job;
    tattr.BASE_PRIORITY = 2;
    tattr.PERIOD        = 25000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 25000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[0]), &ret);
    CHECK_CODE("CREATE_PROCESS(taskC1)", ret);
    START(arinc_threads[0], &ret);
    CHECK_CODE("START(taskC1)", ret);

    /* 5. Task: taskC2 (AADL: TskC2)  Period=50ms Priority=3 */
    strcpy(tattr.NAME, "taskC2");
    tattr.ENTRY_POINT   = taskC2_job;
    tattr.BASE_PRIORITY = 3;
    tattr.PERIOD        = 50000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 50000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[1]), &ret);
    CHECK_CODE("CREATE_PROCESS(taskC2)", ret);
    START(arinc_threads[1], &ret);
    CHECK_CODE("START(taskC2)", ret);

    /* 6. Task: taskC3 (AADL: TskC3)  Period=100ms Priority=4 */
    strcpy(tattr.NAME, "taskC3");
    tattr.ENTRY_POINT   = taskC3_job;
    tattr.BASE_PRIORITY = 4;
    tattr.PERIOD        = 100000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 100000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[2]), &ret);
    CHECK_CODE("CREATE_PROCESS(taskC3)", ret);
    START(arinc_threads[2], &ret);
    CHECK_CODE("START(taskC3)", ret);

    /* 7. Queuing port: cmd_out (SOURCE) */
    CREATE_QUEUING_PORT(
        "cmd_out",
        sizeof(integer),
        4,
        SOURCE,
        FIFO,
        &(pc_cmd_out_id), &ret);
    CHECK_CODE("CREATE_QUEUING_PORT(cmd_out)", ret);

    /* 8. Switch to NORMAL operating mode */
    SET_PARTITION_MODE(NORMAL, &ret);
    CHECK_CODE("SET_PARTITION_MODE(NORMAL)", ret);
    return;
}
