#ifndef __PC_GENERATED_SUBPROGRAMS_H_
#define __PC_GENERATED_SUBPROGRAMS_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: pc  AADL: PC.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

#include "gtypes.h"


#endif
