#include "globals.h"
/*****************************************************/

/*  This file was automatically generated by IMA2C */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run IMA2C     */

/*****************************************************/