#include <os/pos/apex/apexLib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  Partition: ps4 (P4)  Module: M3                 */
/*  Task activity bodies - generated by IMA2C       */
/*****************************************************/

#define SZ 1024

/* ================================================================== */
/*  task41  (AADL: Tsk41)                                             */
/*  Period=25ms  Priority=2  Dispatch_Absolute_Time=0ms               */
/*  No inter- or intra-partition communication                        */
/* ================================================================== */
void* task41_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;

    while (1)
    {
        /* No port operations for task41 */

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task41)", ret);
    }
}

/* ================================================================== */
/*  task42  (AADL: Tsk42)                                             */
/*  Period=50ms  Priority=3  Dispatch_Absolute_Time=0ms               */
/*  Inter-partition READS:  order_in   (QUEUING DESTINATION)          */
/*  Inter-partition WRITES: queueingout (QUEUING SOURCE)              */
/* ================================================================== */
extern QUEUING_PORT_ID_TYPE ps4_order_in_id;
extern QUEUING_PORT_ID_TYPE ps4_queueingout_id;

void* task42_job(void)
{
    RETURN_CODE_TYPE    ret = NO_ERROR;
    MESSAGE_SIZE_TYPE   order_in_len;

    integer ps4_order_in_val    = 0;
    integer ps4_queueingout_val = 0;

    while (1)
    {
        /* ---- RECEIVE from inter-partition QUEUING port order_in ---- */
        RECEIVE_QUEUING_MESSAGE(ps4_order_in_id,
                                5000000ll,           /* TIME_OUT: 5 ms */
                                (MESSAGE_ADDR_TYPE)&ps4_order_in_val,
                                &order_in_len,
                                &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(order_in)", ret);

        /* ---- User computation ---- */
        ps4_queueingout_val = ps4_order_in_val;     /* placeholder */

        /* ---- SEND to inter-partition QUEUING port queueingout ---- */
        SEND_QUEUING_MESSAGE(ps4_queueingout_id,
                             (MESSAGE_ADDR_TYPE)&ps4_queueingout_val,
                             sizeof(integer),
                             5000000ll,              /* TIME_OUT: 5 ms */
                             &ret);
        CHECK_CODE("SEND_QUEUING_MESSAGE(queueingout)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task42)", ret);
    }
}

/* ================================================================== */
/*  task43  (AADL: Tsk43)                                             */
/*  Period=50ms  Priority=4  Dispatch_Absolute_Time=0ms               */
/*  Inter-partition READS:  queueingin (QUEUING DESTINATION)          */
/* ================================================================== */
extern QUEUING_PORT_ID_TYPE ps4_queueingin_id;

void* task43_job(void)
{
    RETURN_CODE_TYPE    ret = NO_ERROR;
    MESSAGE_SIZE_TYPE   queueingin_len;

    integer ps4_queueingin_val = 0;

    while (1)
    {
        /* ---- RECEIVE from inter-partition QUEUING port queueingin ---- */
        RECEIVE_QUEUING_MESSAGE(ps4_queueingin_id,
                                5000000ll,           /* TIME_OUT: 5 ms */
                                (MESSAGE_ADDR_TYPE)&ps4_queueingin_val,
                                &queueingin_len,
                                &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(queueingin)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task43)", ret);
    }
}

/* ================================================================== */
/*  task44  (AADL: Tsk44)                                             */
/*  Period=100ms  Priority=5  Dispatch_Absolute_Time=0ms              */
/*  No inter- or intra-partition communication                        */
/* ================================================================== */
void* task44_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;

    while (1)
    {
        /* No port operations for task44 */

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task44)", ret);
    }
}

/* ================================================================== */
/*  task45  (AADL: Tsk45)                                             */
/*  Period=200ms  Priority=6  Dispatch_Absolute_Time=0ms              */
/*  No inter- or intra-partition communication                        */
/* ================================================================== */
void* task45_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;

    while (1)
    {
        /* No port operations for task45 */

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task45)", ret);
    }
}
