#ifndef __IMA2C_GENERATED_ACTIVITY_H_
#define __IMA2C_GENERATED_ACTIVITY_H_ 

/*****************************************************/

/*  This file was automatically generated by IMA2C */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run IMA2C     */

/*****************************************************/
/*  Periodic  task : task41 */
void* task41_job (void);


/*  Periodic  task : task42 */
void* task42_job (void);


/*  Periodic  task : task43 */
void* task43_job (void);


/*  Periodic  task : task44 */
void* task44_job (void);


/*  Periodic  task : task45 */
void* task45_job (void);



#endif