#include <os/pos/apex/apexLib.h>
#include "deployment.h"
/*****************************************************/

/*  This file was automatically generated by DIMA2C */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run DIMA2C     */

/*****************************************************/


