#ifndef __IMA2C_GENERATED_DEPLOYMENT_H_
#define __IMA2C_GENERATED_DEPLOYMENT_H_ 

/*****************************************************/

/*  This file was automatically generated by IMA2C */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run IMA2C     */

/*****************************************************/


#define IMA2C_RUNTIME_ACoreOS653 1

#define ACoreOS653_GENERATED_CODE 1

#define ACoreOS653_CONFIG_NB_THREADS 5

#define ACoreOS653_CONFIG_NB_QUEUEINGS 3

#define ACoreOS653_NEEDS_ARINC653_PARTITION 1

#define ACoreOS653_NEEDS_ARINC653_PROCESS 1

#define ACoreOS653_NEEDS_ARINC653_QUEUEING 1

#define ACoreOS653_NEEDS_ARINC653_SAMPLING 1

#define ACoreOS653_NEEDS_ARINC653_BUFFER 1

#define ACoreOS653_NEEDS_ARINC653_BLACKBOARD 1

#define ACoreOS653_NEEDS_ARINC653_SEMAPHORE 1

#define ACoreOS653_NEEDS_ARINC653_EVENT 1

#define ACoreOS653_NEEDS_MIDDLEWARE 1

#define ACoreOS653_CONFIG_STACKS_SIZE 24576

#define ACoreOS653_NEEDS_ARINC653_TIME 1


#endif
