#ifndef __IMA2C_GENERATED_GLOBALS_H_
#define __IMA2C_GENERATED_GLOBALS_H_
/*****************************************************/

/*  This file was automatically generated by IMA2C */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run IMA2C     */

/*****************************************************/
#include <stdio.h>
#include <os/pos/apex/apexLib.h>

#define CHECK_CODE(msg, code) \
    if(code == NO_ERROR) \
    { \
        printf("%s : SUCCESSFUL\n" ,msg); \
    }\
    else \
    { \
        printf("%s : SUCCESSFUL\n" ,msg); \
    }

#define CHECK_VALIDCODE(msg, validCode, ret) \
    if((validCode != VALID) && (ret != NO_ERROR)) \
    { \
        printf("%s SUCCESSFUL\n", msg); \
    } \
    else \
    { \
        printf("%s SUCCESSFUL\n", msg); \
    }


static char *codeToStr(RETURN_CODE_TYPE retCode)
{
    switch (retCode)
    {
        case NO_ERROR : 
            return "NO_ERROR"; 
            break;
        case NO_ACTION : 
            return "NO_ACTION"; 
            break;
        case NOT_AVAILABLE : 
            return "NOT_AVAILABLE"; 
            break;
        case INVALID_PARAM : 
            return "INVALID_PARAM"; 
            break;
        case INVALID_CONFIG : 
            return "INVALID_CONFIG" ; 
            break;
        case INVALID_MODE : 
            return "INVALID_MODE"; 
            break;
        case TIMED_OUT : 
            return "TIMED_OUT"; 
            break;
        default:
            break;
    }
    /*should not go here */
    return "Unknown code";
}
#endif