#ifndef __CTRL_GENERATED_ACTIVITY_H_
#define __CTRL_GENERATED_ACTIVITY_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ctrl  AADL: CTRL.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

/* Periodic task: taskT1 (AADL: TskT1)
 * Period=25ms  Priority=2  Stack=8192B */
void* taskT1_job(void);

/* Periodic task: taskT2 (AADL: TskT2)
 * Period=50ms  Priority=3  Stack=8192B */
void* taskT2_job(void);

/* Periodic task: taskT3 (AADL: TskT3)
 * Period=100ms  Priority=4  Stack=8192B */
void* taskT3_job(void);

#endif
