#include <os/pos/apex/apexLib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ctrl  AADL: CTRL.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


#define SZ 1024

/* ================================================================== */
/*  taskT1  (AADL: TskT1)
 *  Period=25ms  Priority=2  Dispatch_Abs=0ms
 *  Inter-partition READS:  nav_in (QUEUING DEST)
 *  Intra-partition WRITES (BUF): buf_ctrl
 * ================================================================== */
extern BUFFER_ID_TYPE ctrl_buf_ctrl_id;
extern QUEUING_PORT_ID_TYPE ctrl_nav_in_id;

void* taskT1_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* RECEIVE inter-partition QUEUING: nav_in */
        RECEIVE_QUEUING_MESSAGE(ctrl_nav_in_id,
            5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(nav_in)", ret);

        /* WRITE intra-partition BUFFER: buf_ctrl */
        WRITE_BUFFER(ctrl_buf_ctrl_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer),
            5000000ll, &ret);
        CHECK_CODE("WRITE_BUFFER(buf_ctrl)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(taskT1)", ret);
    }
}

/* ================================================================== */
/*  taskT2  (AADL: TskT2)
 *  Period=50ms  Priority=3  Dispatch_Abs=0ms
 *  Intra-partition READS  (BUF): buf_ctrl
 * ================================================================== */
extern BUFFER_ID_TYPE ctrl_buf_ctrl_id;

void* taskT2_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* READ intra-partition BUFFER: buf_ctrl */
        READ_BUFFER(ctrl_buf_ctrl_id, 5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("READ_BUFFER(buf_ctrl)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(taskT2)", ret);
    }
}

/* ================================================================== */
/*  taskT3  (AADL: TskT3)
 *  Period=100ms  Priority=4  Dispatch_Abs=0ms
 *  Inter-partition WRITES: ctrl_out (QUEUING SOURCE)
 * ================================================================== */
extern QUEUING_PORT_ID_TYPE ctrl_ctrl_out_id;

void* taskT3_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* SEND inter-partition QUEUING: ctrl_out */
        SEND_QUEUING_MESSAGE(ctrl_ctrl_out_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer),
            5000000ll, &ret);
        CHECK_CODE("SEND_QUEUING_MESSAGE(ctrl_out)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(taskT3)", ret);
    }
}

