#ifndef __CTRL_GENERATED_GTYPES_H_
#define __CTRL_GENERATED_GTYPES_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ctrl  AADL: CTRL.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

#include <os/pos/apex/apexLib.h>

typedef int integer;

#endif
