#include <os/pos/apex/apexLib.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ctrl  AADL: CTRL.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


PROCESS_ID_TYPE arinc_threads[ACoreOS653_CONFIG_NB_THREADS];

/* ---- Inter-partition ports ---- */
QUEUING_PORT_ID_TYPE  ctrl_nav_in_id;
QUEUING_PORT_ID_TYPE  ctrl_ctrl_out_id;

/* ---- Intra-partition buffers ---- */
BUFFER_ID_TYPE ctrl_buf_ctrl_id;  /* taskT1 -> taskT2 */

void appMain(void)
{
    PROCESS_ATTRIBUTE_TYPE tattr;
    RETURN_CODE_TYPE ret = NO_ERROR;

    /* 1. Buffer: buf_ctrl  (taskT1 -> taskT2) */
    CREATE_BUFFER(
        "buf_ctrl",
        sizeof(integer),
        4,
        FIFO,
        &(ctrl_buf_ctrl_id), &ret);
    CHECK_CODE("CREATE_BUFFER(buf_ctrl)", ret);

    /* 2. Task: taskT1 (AADL: TskT1)  Period=25ms Priority=2 */
    strcpy(tattr.NAME, "taskT1");
    tattr.ENTRY_POINT   = taskT1_job;
    tattr.BASE_PRIORITY = 2;
    tattr.PERIOD        = 25000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 25000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[0]), &ret);
    CHECK_CODE("CREATE_PROCESS(taskT1)", ret);
    START(arinc_threads[0], &ret);
    CHECK_CODE("START(taskT1)", ret);

    /* 3. Task: taskT2 (AADL: TskT2)  Period=50ms Priority=3 */
    strcpy(tattr.NAME, "taskT2");
    tattr.ENTRY_POINT   = taskT2_job;
    tattr.BASE_PRIORITY = 3;
    tattr.PERIOD        = 50000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 50000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[1]), &ret);
    CHECK_CODE("CREATE_PROCESS(taskT2)", ret);
    START(arinc_threads[1], &ret);
    CHECK_CODE("START(taskT2)", ret);

    /* 4. Task: taskT3 (AADL: TskT3)  Period=100ms Priority=4 */
    strcpy(tattr.NAME, "taskT3");
    tattr.ENTRY_POINT   = taskT3_job;
    tattr.BASE_PRIORITY = 4;
    tattr.PERIOD        = 100000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 100000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[2]), &ret);
    CHECK_CODE("CREATE_PROCESS(taskT3)", ret);
    START(arinc_threads[2], &ret);
    CHECK_CODE("START(taskT3)", ret);

    /* 5. Queuing port: nav_in (DESTINATION) */
    CREATE_QUEUING_PORT(
        "nav_in",
        sizeof(integer),
        4,
        DESTINATION,
        FIFO,
        &(ctrl_nav_in_id), &ret);
    CHECK_CODE("CREATE_QUEUING_PORT(nav_in)", ret);

    /* 6. Queuing port: ctrl_out (SOURCE) */
    CREATE_QUEUING_PORT(
        "ctrl_out",
        sizeof(integer),
        4,
        SOURCE,
        FIFO,
        &(ctrl_ctrl_out_id), &ret);
    CHECK_CODE("CREATE_QUEUING_PORT(ctrl_out)", ret);

    /* 7. Switch to NORMAL operating mode */
    SET_PARTITION_MODE(NORMAL, &ret);
    CHECK_CODE("SET_PARTITION_MODE(NORMAL)", ret);
    return;
}
