#ifndef __CTRL_GENERATED_SUBPROGRAMS_H_
#define __CTRL_GENERATED_SUBPROGRAMS_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ctrl  AADL: CTRL.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

#include "gtypes.h"


#endif
