#ifndef __DISP_GENERATED_ACTIVITY_H_
#define __DISP_GENERATED_ACTIVITY_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: disp  AADL: DISP.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

/* Periodic task: taskD1 (AADL: TskD1)
 * Period=50ms  Priority=2  Stack=8192B */
void* taskD1_job(void);

/* Periodic task: taskD2 (AADL: TskD2)
 * Period=100ms  Priority=3  Stack=8192B */
void* taskD2_job(void);

#endif
