#ifndef __DISP_GENERATED_DEPLOYMENT_H_
#define __DISP_GENERATED_DEPLOYMENT_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: disp  AADL: DISP.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

#define IMA2C_RUNTIME_ACoreOS653 1
#define ACoreOS653_GENERATED_CODE 1

#define ACoreOS653_CONFIG_NB_THREADS     2
#define ACoreOS653_CONFIG_NB_SAMPLINGS   1
#define ACoreOS653_CONFIG_NB_QUEUEINGS   1
#define ACoreOS653_CONFIG_NB_BLACKBOARDS 1
#define ACoreOS653_CONFIG_NB_BUFFERS     0

#define ACoreOS653_NEEDS_ARINC653_PARTITION  1
#define ACoreOS653_NEEDS_ARINC653_PROCESS    1
#define ACoreOS653_NEEDS_ARINC653_SAMPLING   1
#define ACoreOS653_NEEDS_ARINC653_QUEUEING   1
#define ACoreOS653_NEEDS_ARINC653_BLACKBOARD 1
#define ACoreOS653_NEEDS_ARINC653_BUFFER     0
#define ACoreOS653_NEEDS_ARINC653_SEMAPHORE  0
#define ACoreOS653_NEEDS_ARINC653_EVENT      0
#define ACoreOS653_NEEDS_MIDDLEWARE          1
#define ACoreOS653_NEEDS_ARINC653_TIME       1

#define ACoreOS653_CONFIG_STACKS_SIZE 16384

#endif
