#ifndef __DISP_GENERATED_GTYPES_H_
#define __DISP_GENERATED_GTYPES_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: disp  AADL: DISP.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

#include <os/pos/apex/apexLib.h>

typedef int integer;

#endif
