#ifndef __DISP_GENERATED_SUBPROGRAMS_H_
#define __DISP_GENERATED_SUBPROGRAMS_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: disp  AADL: DISP.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

#include "gtypes.h"


#endif
