#ifndef __MON_GENERATED_ACTIVITY_H_
#define __MON_GENERATED_ACTIVITY_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: mon  AADL: MON.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

/* Periodic task: taskM1 (AADL: TskM1)
 * Period=100ms  Priority=2  Stack=8192B */
void* taskM1_job(void);

#endif
