#include <os/pos/apex/apexLib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: mon  AADL: MON.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


#define SZ 1024

/* ================================================================== */
/*  taskM1  (AADL: TskM1)
 *  Period=100ms  Priority=2  Dispatch_Abs=0ms
 *  Inter-partition READS:  status_in (SAMPLING DEST)
 * ================================================================== */
extern SAMPLING_PORT_ID_TYPE mon_status_in_id;

void* taskM1_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    VALIDITY_TYPE    validity;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* READ inter-partition SAMPLING: status_in */
        READ_SAMPLING_MESSAGE(mon_status_in_id,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &validity, &ret);
        CHECK_VALIDCODE("READ_SAMPLING_MESSAGE(status_in)", validity, ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(taskM1)", ret);
    }
}

