#ifndef __MON_GENERATED_GTYPES_H_
#define __MON_GENERATED_GTYPES_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: mon  AADL: MON.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

#include <os/pos/apex/apexLib.h>

typedef int integer;

#endif
