#include <os/pos/apex/apexLib.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: mon  AADL: MON.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


PROCESS_ID_TYPE arinc_threads[ACoreOS653_CONFIG_NB_THREADS];

/* ---- Inter-partition ports ---- */
SAMPLING_PORT_ID_TYPE mon_status_in_id;

void appMain(void)
{
    PROCESS_ATTRIBUTE_TYPE tattr;
    RETURN_CODE_TYPE ret = NO_ERROR;

    /* 1. Sampling port: status_in (DESTINATION) */
    CREATE_SAMPLING_PORT(
        "status_in",
        sizeof(integer),
        DESTINATION,
        100000000ll,
        &(mon_status_in_id), &ret);
    CHECK_CODE("CREATE_SAMPLING_PORT(status_in)", ret);

    /* 2. Task: taskM1 (AADL: TskM1)  Period=100ms Priority=2 */
    strcpy(tattr.NAME, "taskM1");
    tattr.ENTRY_POINT   = taskM1_job;
    tattr.BASE_PRIORITY = 2;
    tattr.PERIOD        = 100000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 100000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[0]), &ret);
    CHECK_CODE("CREATE_PROCESS(taskM1)", ret);
    START(arinc_threads[0], &ret);
    CHECK_CODE("START(taskM1)", ret);

    /* 3. Switch to NORMAL operating mode */
    SET_PARTITION_MODE(NORMAL, &ret);
    CHECK_CODE("SET_PARTITION_MODE(NORMAL)", ret);
    return;
}
