package ima2c.conf;

import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.Path;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.jface.viewers.IStructuredSelection;
import org.eclipse.ui.PlatformUI;
import org.osate.aadl2.instance.impl.SystemInstanceImpl;
import org.osate.aadl2.presentation.Aadl2ModelEditor;

public class CodeGenConf {

	// private static String C_CODE_GEN_PATH = getGenPath();


	public static String getGenPath() {
		Aadl2ModelEditor a = (Aadl2ModelEditor) PlatformUI.getWorkbench().getActiveWorkbenchWindow().getActivePage()
				.getActiveEditor();
		SystemInstanceImpl system = (SystemInstanceImpl) ((IStructuredSelection) a.getSelection()).getFirstElement();
		Resource res = system.eResource();
		org.eclipse.emf.common.util.URI uri = res.getURI();
		IPath path = ResourcesPlugin.getWorkspace().getRoot().getFile(new Path(uri.toPlatformString(true)))
				.getFullPath();

		String[] segments = path.segments();
		String projectName = segments[0];

		IProject prj = ResourcesPlugin.getWorkspace().getRoot().getProject(projectName);
		String directoryName = prj.getLocation().toString();
		return directoryName + "/C_Code_Gen";
	}

	public static String getAadlFilePath() {
		Aadl2ModelEditor a = (Aadl2ModelEditor) PlatformUI.getWorkbench().getActiveWorkbenchWindow().getActivePage()
				.getActiveEditor();
		SystemInstanceImpl system = (SystemInstanceImpl) ((IStructuredSelection) a.getSelection()).getFirstElement();
		Resource res = system.eResource();
		org.eclipse.emf.common.util.URI uri = res.getURI();
		IPath path = ResourcesPlugin.getWorkspace().getRoot().getFile(new Path(uri.toPlatformString(true)))
				.getFullPath();

		String[] segments = path.segments();

		String projectName = segments[0];

		IProject prj = ResourcesPlugin.getWorkspace().getRoot().getProject(projectName);
		String directoryName = prj.getLocation().toString();
		StringBuilder strb = new StringBuilder(directoryName);
		for (int i = 1; i < segments.length - 2; i++) {
			strb.append("/" + segments[i]);
		}
		return strb.toString();
	}

	/**
	 * kernel configuration file
	 */
	private final static String MODULE_XML = "module.xml";

	/**
	 * partition configuration file
	 */
	private final static String DEPLOYMENT_H = "deployment.h";
	private final static String DEPLOYMENT_C = "deployment.c";

	/*
	 * Functions transformed by subroutines or functions generated by heterogeneous
	 * components
	 */
	private final static String SUBPROGRAMS_H = "subprograms.h";
	private final static String SUBPROGRAMS_C = "subprograms.c";

	/**
	 * Periodic or sporadic thread generation code files
	 */
	private final static String ACTIVITY_H = "activity.h";
	private final static String ACTIVITY_C = "activity.c";

	private final static String APERIODIC_H = "aperiodic.h";
	private final static String APERIODIC_C = "aperiodic.c";

	/**
	 * main partition run file
	 */
	private final static String MAIN_C = "main.c";

	private final static String GTYPES_H = "gtypes.h";
	private final static String GTYPES_C = "gtypes.c";

	/*
	 * data type files, as global variables
	 */
	private final static String DATATYPE_H = "DataType.h";

	/*
	 * Consider storing global variables at runtime
	 */
	private final static String GLOBALS_H = "globals.h";
	private final static String GLOBALS_C = "globals.c";

	public static String getCCodeGenPath() {
		return getGenPath();
	}

	public static String getCCodeGenPath(String partitionName) {
		return getGenPath() + "/" + partitionName;
	}

	public static String getModuleXml() {
		return MODULE_XML;
	}

	public static String getCoreXml(String moduleName) {
		return getGenPath() + "/" + moduleName;
	}

	public static String getDeploymentH() {
		return DEPLOYMENT_H;
	}

	public static String getDeploymentC() {
		return DEPLOYMENT_C;
	}

	public static String getSubprogramsH() {
		return SUBPROGRAMS_H;
	}

	public static String getSubprogramsC() {
		return SUBPROGRAMS_C;
	}

	public static String getActivityH() {
		return ACTIVITY_H;
	}

	public static String getActivityC() {
		return ACTIVITY_C;
	}

	public static String getMainC() {
		return MAIN_C;
	}

	public static String getGtypesH() {
		return GTYPES_H;
	}

	public static String getGtypesC() {
		return GTYPES_C;
	}

	public static String getDataTypeH() {
		return DATATYPE_H;
	}

	public static String getGlobalsH() {
		return GLOBALS_H;
	}

	public static String getGlobalsC() {
		return GLOBALS_C;
	}

	public static String getAperiodicH() {
		return APERIODIC_H;
	}

	public static String getAperiodicC() {
		return APERIODIC_C;
	}

}
