#ifndef __PS3_GENERATED_ACTIVITY_H_
#define __PS3_GENERATED_ACTIVITY_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ps3  AADL: P3.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

/* Periodic task: task31 (AADL: Tsk31)
 * Period=25ms  Priority=2  Stack=8192B */
void* task31_job(void);

/* Periodic task: task32 (AADL: Tsk32)
 * Period=50ms  Priority=3  Stack=8192B */
void* task32_job(void);

/* Periodic task: task33 (AADL: Tsk33)
 * Period=50ms  Priority=4  Stack=8192B */
void* task33_job(void);

#endif
