#include <os/pos/apex/apexLib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ps3  AADL: P3.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


#define SZ 1024

/* ================================================================== */
/*  task31  (AADL: Tsk31)
 *  Period=25ms  Priority=2  Dispatch_Abs=0ms
 *  Inter-partition READS:  order_in (QUEUING DEST)
 * ================================================================== */
extern QUEUING_PORT_ID_TYPE ps3_order_in_id;

void* task31_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* RECEIVE inter-partition QUEUING: order_in */
        RECEIVE_QUEUING_MESSAGE(ps3_order_in_id,
            5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(order_in)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task31)", ret);
    }
}

/* ================================================================== */
/*  task32  (AADL: Tsk32)
 *  Period=50ms  Priority=3  Dispatch_Abs=0ms
 *  Inter-partition READS:  order_in (QUEUING DEST)
 * ================================================================== */
extern QUEUING_PORT_ID_TYPE ps3_order_in_id;

void* task32_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* RECEIVE inter-partition QUEUING: order_in */
        RECEIVE_QUEUING_MESSAGE(ps3_order_in_id,
            5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(order_in)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task32)", ret);
    }
}

/* ================================================================== */
/*  task33  (AADL: Tsk33)
 *  Period=50ms  Priority=4  Dispatch_Abs=0ms
 *  Inter-partition READS:  queueingin (QUEUING DEST)
 * ================================================================== */
extern QUEUING_PORT_ID_TYPE ps3_queueingin_id;

void* task33_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* RECEIVE inter-partition QUEUING: queueingin */
        RECEIVE_QUEUING_MESSAGE(ps3_queueingin_id,
            5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(queueingin)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task33)", ret);
    }
}

