/* ==============================================================
 *  FILE:    activity.c
 *  ROLE:    任务循环体实现（Task Job Implementations）
 *
 *  IMA 架构层次：线程层（Thread Layer）
 *  IMA 分区：ps3 (P3)     模块：M2 (arinckernel.module2)
 *  对应 AADL 文件：DIMA_threads.aadl
 *    AADL thread Tsk31/Tsk32/Tsk33 各自对应一个周期性任务。
 *
 *  本文件是 ps3 分区的核心执行代码，实现各任务的 while(1) 主循环。
 *  每个任务的执行流程为：
 *    1. 调用 ARINC 653 APEX 服务收发消息（RECEIVE/SEND/READ/WRITE）
 *    2. （可选）调用 subprograms.c 中的用户计算函数
 *    3. 调用 PERIODIC_WAIT() 挂起，等待下一个调度周期
 *
 *  ps3 分区特点：
 *    - 所有任务只有分区间接收端口（QUEUING DESTINATION）
 *    - 无分区内通信（无黑板、无缓冲区）
 *    - 无子程序调用
 * ==============================================================*/

#include <os/pos/apex/apexLib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ps3  AADL: P3.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


#define SZ 1024

/* ================================================================== */
/*  task31  (AADL: Tsk31)
 *  Period=25ms  Priority=2  Dispatch_Abs=0ms
 *  Inter-partition READS:  order_in (QUEUING DEST)
 * ================================================================== */
extern QUEUING_PORT_ID_TYPE ps3_order_in_id;

void* task31_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* RECEIVE inter-partition QUEUING: order_in */
        RECEIVE_QUEUING_MESSAGE(ps3_order_in_id,
            5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(order_in)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task31)", ret);
    }
}

/* ================================================================== */
/*  task32  (AADL: Tsk32)
 *  Period=50ms  Priority=3  Dispatch_Abs=0ms
 *  Inter-partition READS:  order_in (QUEUING DEST)
 * ================================================================== */
extern QUEUING_PORT_ID_TYPE ps3_order_in_id;

void* task32_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* RECEIVE inter-partition QUEUING: order_in */
        RECEIVE_QUEUING_MESSAGE(ps3_order_in_id,
            5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(order_in)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task32)", ret);
    }
}

/* ================================================================== */
/*  task33  (AADL: Tsk33)
 *  Period=50ms  Priority=4  Dispatch_Abs=0ms
 *  Inter-partition READS:  queueingin (QUEUING DEST)
 * ================================================================== */
extern QUEUING_PORT_ID_TYPE ps3_queueingin_id;

void* task33_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* RECEIVE inter-partition QUEUING: queueingin */
        RECEIVE_QUEUING_MESSAGE(ps3_queueingin_id,
            5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(queueingin)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task33)", ret);
    }
}

