#ifndef __PS3_GENERATED_GTYPES_H_
#define __PS3_GENERATED_GTYPES_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ps3  AADL: P3.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

#include <os/pos/apex/apexLib.h>

typedef int integer;

#endif
