/* ==============================================================
 *  FILE:    main.c
 *  ROLE:    分区入口与资源初始化（Partition Entry & Resource Init）
 *
 *  IMA 架构层次：分区层（Partition Layer）
 *  IMA 分区：ps3 (P3)     模块：M2 (arinckernel.module2)
 *  对应 AADL 文件：
 *    - DIMA_partitions.aadl ：分区定义（端口、资源声明）
 *    - DIMA_models.aadl     ：分区绑定到处理器模块
 *    - DIMA_threads.aadl    ：线程（任务）属性（周期、优先级等）
 *
 *  appMain() 是 ARINC 653 操作系统启动后调用的分区入口函数。
 *  它只执行一次，负责创建分区所需的全部资源，然后切换到 NORMAL 模式。
 *
 *  执行步骤：
 *    1. CREATE_QUEUING_PORT / CREATE_SAMPLING_PORT — 创建分区间通信端口
 *       对应 AADL: partition 的 feature（in/out data port / event data port）
 *    2. CREATE_BLACKBOARD / CREATE_BUFFER          — 创建分区内通信资源
 *       对应 AADL: thread 之间的 data access 连接
 *    3. CREATE_PROCESS + START                     — 创建并启动各任务
 *       对应 AADL: thread 及其 Period、Priority 属性
 *    4. SET_PARTITION_MODE(NORMAL)                 — 切换到正常运行模式
 *       此后 appMain 返回，RTOS 开始周期调度各任务
 * ==============================================================*/
#include <os/pos/apex/apexLib.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: ps3  AADL: P3.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


PROCESS_ID_TYPE arinc_threads[ACoreOS653_CONFIG_NB_THREADS];

/* ---- Inter-partition ports ---- */
QUEUING_PORT_ID_TYPE  ps3_order_in_id;
QUEUING_PORT_ID_TYPE  ps3_queueingin_id;

void appMain(void)
{
    PROCESS_ATTRIBUTE_TYPE tattr;
    RETURN_CODE_TYPE ret = NO_ERROR;

    /* 1. Task: task31 (AADL: Tsk31)  Period=25ms Priority=2 */
    strcpy(tattr.NAME, "task31");
    tattr.ENTRY_POINT   = task31_job;
    tattr.BASE_PRIORITY = 2;
    tattr.PERIOD        = 25000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 50000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[0]), &ret);
    CHECK_CODE("CREATE_PROCESS(task31)", ret);
    START(arinc_threads[0], &ret);
    CHECK_CODE("START(task31)", ret);

    /* 2. Task: task32 (AADL: Tsk32)  Period=50ms Priority=3 */
    strcpy(tattr.NAME, "task32");
    tattr.ENTRY_POINT   = task32_job;
    tattr.BASE_PRIORITY = 3;
    tattr.PERIOD        = 50000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 50000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[1]), &ret);
    CHECK_CODE("CREATE_PROCESS(task32)", ret);
    START(arinc_threads[1], &ret);
    CHECK_CODE("START(task32)", ret);

    /* 3. Task: task33 (AADL: Tsk33)  Period=50ms Priority=4 */
    strcpy(tattr.NAME, "task33");
    tattr.ENTRY_POINT   = task33_job;
    tattr.BASE_PRIORITY = 4;
    tattr.PERIOD        = 50000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 50000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[2]), &ret);
    CHECK_CODE("CREATE_PROCESS(task33)", ret);
    START(arinc_threads[2], &ret);
    CHECK_CODE("START(task33)", ret);

    /* 4. Queuing port: order_in (DESTINATION) */
    CREATE_QUEUING_PORT(
        "order_in",
        sizeof(integer),
        10,
        DESTINATION,
        FIFO,
        &(ps3_order_in_id), &ret);
    CHECK_CODE("CREATE_QUEUING_PORT(order_in)", ret);

    /* 5. Queuing port: queueingin (DESTINATION) */
    CREATE_QUEUING_PORT(
        "queueingin",
        sizeof(integer),
        4,
        DESTINATION,
        FIFO,
        &(ps3_queueingin_id), &ret);
    CHECK_CODE("CREATE_QUEUING_PORT(queueingin)", ret);

    /* 6. Switch to NORMAL operating mode */
    SET_PARTITION_MODE(NORMAL, &ret);
    CHECK_CODE("SET_PARTITION_MODE(NORMAL)", ret);
    return;
}
