package ima2c.log;

public class LogMsg {
	public static String EVERYTHING_OK_IN_AADL2C = "Everything is OK in AADL2C!";
	public static String EVERYTHING_OK_IN_AADL2XML = "Everything is OK in AADL2XML!";

	public static String SCADE2C_FINISHED = "C code generated by SCADE successfully !";
	public static String SDL2C_FINISHED = "C code generated by SDL successfully !";
	public static String SIGNAL2C_FINISHED = "C code generated by SCADE successfully !";

	public static String SELECT_ERROR = "The component selection is error !";
	public static String INTERNAL_BUGS_IN_MODEL = "Internal Bugs in model!";
}
