#include <os/pos/apex/apexLib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  Partition: ps2 (P2)  Module: M1                 */
/*  Task activity bodies - generated by IMA2C       */
/*****************************************************/

#define SZ 1024

/* ================================================================== */
/*  task21  (AADL: Tsk21)                                             */
/*  Period=50ms  Priority=2  Dispatch_Absolute_Time=0ms               */
/*  Inter-partition READS:  pr2samplingin (SAMPLING DESTINATION)      */
/*  Intra-partition READS:  buf_order    (from task22)                */
/*  Intra-partition WRITES: bb_acc3      (to task22)                  */
/* ================================================================== */
extern SAMPLING_PORT_ID_TYPE ps2_pr2samplingin_id;
extern BLACKBOARD_ID_TYPE    ps2_bb_acc3_id;
extern BUFFER_ID_TYPE        ps2_buf_order_id;

void* task21_job(void)
{
    RETURN_CODE_TYPE    ret = NO_ERROR;
    VALIDITY_TYPE       validity;
    MESSAGE_SIZE_TYPE   sampling_len, buf_order_len;

    integer ps2_pr2samplingin_val = 0;
    integer ps2_buf_order_val     = 0;
    integer ps2_bb_acc3_val       = 0;

    while (1)
    {
        /* ---- READ from inter-partition SAMPLING port pr2samplingin ---- */
        READ_SAMPLING_MESSAGE(ps2_pr2samplingin_id,
                              (MESSAGE_ADDR_TYPE)&ps2_pr2samplingin_val,
                              &sampling_len,
                              &validity,
                              &ret);
        CHECK_VALIDCODE("READ_SAMPLING_MESSAGE(pr2samplingin)", validity, ret);

        /* ---- Call user subprogram: commandboard_receiveinput_spg ---- */
        commandboard_receiveinput_spg(&ps2_pr2samplingin_val, &ps2_bb_acc3_val);

        /* ---- Call user subprogram: commandboard_printinfos_spg ---- */
        commandboard_printinfos_spg(&ps2_bb_acc3_val);

        /* ---- READ from intra-partition BUFFER buf_order (task22 writes) ---- */
        READ_BUFFER(ps2_buf_order_id,
                    0ll,                               /* TIME_OUT: poll */
                    (MESSAGE_ADDR_TYPE)&ps2_buf_order_val,
                    &buf_order_len,
                    &ret);
        CHECK_CODE("READ_BUFFER(buf_order)", ret);

        /* ---- WRITE to intra-partition BLACKBOARD bb_acc3 (task22 reads) ---- */
        DISPLAY_BLACKBOARD(ps2_bb_acc3_id,
                           (MESSAGE_ADDR_TYPE)&ps2_bb_acc3_val,
                           sizeof(integer),
                           &ret);
        CHECK_CODE("DISPLAY_BLACKBOARD(bb_acc3)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task21)", ret);
    }
}

/* ================================================================== */
/*  task22  (AADL: Tsk22)                                             */
/*  Period=50ms  Priority=3  Dispatch_Absolute_Time=2ms               */
/*  Intra-partition READS:  bb_acc3  (from task21)                    */
/*                          buf_t3tot2, bb_t3t2  (from task23)        */
/*  Intra-partition WRITES: buf_order (to task21)                     */
/*                          buf_t2tot3, bb_t2t3  (to task23)          */
/* ================================================================== */
extern BLACKBOARD_ID_TYPE ps2_bb_t2t3_id;
extern BLACKBOARD_ID_TYPE ps2_bb_t3t2_id;
extern BUFFER_ID_TYPE     ps2_buf_t2tot3_id;
extern BUFFER_ID_TYPE     ps2_buf_t3tot2_id;

void* task22_job(void)
{
    RETURN_CODE_TYPE    ret = NO_ERROR;
    MESSAGE_SIZE_TYPE   bb_acc3_len, bb_t3t2_len, buf_t3tot2_len;

    integer ps2_bb_acc3_val    = 0;
    integer ps2_buf_t3tot2_val = 0;
    integer ps2_bb_t3t2_val    = 0;
    integer ps2_buf_order_val  = 0;
    integer ps2_buf_t2tot3_val = 0;
    integer ps2_bb_t2t3_val    = 0;

    while (1)
    {
        /* ---- READ from intra-partition BLACKBOARD bb_acc3 (task21 writes) ---- */
        READ_BLACKBOARD(ps2_bb_acc3_id,
                        0ll,
                        (MESSAGE_ADDR_TYPE)&ps2_bb_acc3_val,
                        &bb_acc3_len,
                        &ret);
        CHECK_CODE("READ_BLACKBOARD(bb_acc3)", ret);

        /* ---- READ from intra-partition BUFFER buf_t3tot2 (task23 writes) ---- */
        READ_BUFFER(ps2_buf_t3tot2_id,
                    5000000ll,                         /* TIME_OUT: 5 ms */
                    (MESSAGE_ADDR_TYPE)&ps2_buf_t3tot2_val,
                    &buf_t3tot2_len,
                    &ret);
        CHECK_CODE("READ_BUFFER(buf_t3tot2)", ret);

        /* ---- READ from intra-partition BLACKBOARD bb_t3t2 (task23 writes) ---- */
        READ_BLACKBOARD(ps2_bb_t3t2_id,
                        0ll,
                        (MESSAGE_ADDR_TYPE)&ps2_bb_t3t2_val,
                        &bb_t3t2_len,
                        &ret);
        CHECK_CODE("READ_BLACKBOARD(bb_t3t2)", ret);

        /* ---- User computation ---- */
        ps2_buf_order_val  = ps2_bb_acc3_val;                          /* placeholder */
        ps2_buf_t2tot3_val = ps2_buf_t3tot2_val + ps2_bb_t3t2_val;    /* placeholder */
        ps2_bb_t2t3_val    = ps2_bb_acc3_val;

        /* ---- WRITE to intra-partition BUFFER buf_order (task21 reads) ---- */
        WRITE_BUFFER(ps2_buf_order_id,
                     (MESSAGE_ADDR_TYPE)&ps2_buf_order_val,
                     sizeof(integer),
                     0ll,
                     &ret);
        CHECK_CODE("WRITE_BUFFER(buf_order)", ret);

        /* ---- WRITE to intra-partition BUFFER buf_t2tot3 (task23 reads) ---- */
        WRITE_BUFFER(ps2_buf_t2tot3_id,
                     (MESSAGE_ADDR_TYPE)&ps2_buf_t2tot3_val,
                     sizeof(integer),
                     5000000ll,
                     &ret);
        CHECK_CODE("WRITE_BUFFER(buf_t2tot3)", ret);

        /* ---- WRITE to intra-partition BLACKBOARD bb_t2t3 (task23 reads) ---- */
        DISPLAY_BLACKBOARD(ps2_bb_t2t3_id,
                           (MESSAGE_ADDR_TYPE)&ps2_bb_t2t3_val,
                           sizeof(integer),
                           &ret);
        CHECK_CODE("DISPLAY_BLACKBOARD(bb_t2t3)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task22)", ret);
    }
}

/* ================================================================== */
/*  task23  (AADL: Tsk23)                                             */
/*  Period=100ms  Priority=4  Dispatch_Absolute_Time=0ms              */
/*  Intra-partition READS:  buf_t2tot3, bb_t2t3  (from task22)        */
/*  Intra-partition WRITES: buf_t3tot2, bb_t3t2  (to task22)          */
/*  Inter-partition WRITES: pr2queueingout (QUEUING SOURCE)           */
/* ================================================================== */
extern QUEUING_PORT_ID_TYPE ps2_pr2queueingout_id;

void* task23_job(void)
{
    RETURN_CODE_TYPE    ret = NO_ERROR;
    MESSAGE_SIZE_TYPE   buf_t2tot3_len, bb_t2t3_len;

    integer ps2_buf_t2tot3_val  = 0;
    integer ps2_bb_t2t3_val     = 0;
    integer ps2_buf_t3tot2_val  = 0;
    integer ps2_bb_t3t2_val     = 0;
    integer ps2_pr2queueingout_val = 0;

    while (1)
    {
        /* ---- READ from intra-partition BUFFER buf_t2tot3 (task22 writes) ---- */
        READ_BUFFER(ps2_buf_t2tot3_id,
                    5000000ll,
                    (MESSAGE_ADDR_TYPE)&ps2_buf_t2tot3_val,
                    &buf_t2tot3_len,
                    &ret);
        CHECK_CODE("READ_BUFFER(buf_t2tot3)", ret);

        /* ---- READ from intra-partition BLACKBOARD bb_t2t3 (task22 writes) ---- */
        READ_BLACKBOARD(ps2_bb_t2t3_id,
                        0ll,
                        (MESSAGE_ADDR_TYPE)&ps2_bb_t2t3_val,
                        &bb_t2t3_len,
                        &ret);
        CHECK_CODE("READ_BLACKBOARD(bb_t2t3)", ret);

        /* ---- Call user subprograms ---- */
        commandboard_receiveinput_spg(&ps2_buf_t2tot3_val, &ps2_pr2queueingout_val);
        commandboard_printinfos_spg(&ps2_bb_t2t3_val);

        /* ---- User computation ---- */
        ps2_buf_t3tot2_val = ps2_buf_t2tot3_val;   /* placeholder */
        ps2_bb_t3t2_val    = ps2_bb_t2t3_val;

        /* ---- WRITE to intra-partition BUFFER buf_t3tot2 (task22 reads) ---- */
        WRITE_BUFFER(ps2_buf_t3tot2_id,
                     (MESSAGE_ADDR_TYPE)&ps2_buf_t3tot2_val,
                     sizeof(integer),
                     5000000ll,
                     &ret);
        CHECK_CODE("WRITE_BUFFER(buf_t3tot2)", ret);

        /* ---- WRITE to intra-partition BLACKBOARD bb_t3t2 (task22 reads) ---- */
        DISPLAY_BLACKBOARD(ps2_bb_t3t2_id,
                           (MESSAGE_ADDR_TYPE)&ps2_bb_t3t2_val,
                           sizeof(integer),
                           &ret);
        CHECK_CODE("DISPLAY_BLACKBOARD(bb_t3t2)", ret);

        /* ---- SEND to inter-partition QUEUING port pr2queueingout ---- */
        SEND_QUEUING_MESSAGE(ps2_pr2queueingout_id,
                             (MESSAGE_ADDR_TYPE)&ps2_pr2queueingout_val,
                             sizeof(integer),
                             5000000ll,            /* TIME_OUT: 5 ms */
                             &ret);
        CHECK_CODE("SEND_QUEUING_MESSAGE(pr2queueingout)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task23)", ret);
    }
}
