#ifndef __IMA2C_GENERATED_ACTIVITY_H_
#define __IMA2C_GENERATED_ACTIVITY_H_

/*****************************************************/
/*  This file was automatically generated by IMA2C  */
/*  Partition: ps2 (P2)  Module: M1                 */
/*****************************************************/

/* Periodic task: task21 (Tsk21)
 * Period=50ms  Priority=2  Stack=8KB
 * Reads:  pr2samplingin (sampling DESTINATION), buf_order (from task22)
 * Writes: bb_acc3 (to task22)
 */
void* task21_job(void);

/* Periodic task: task22 (Tsk22)
 * Period=50ms  Priority=3  Stack=8KB
 * Reads:  bb_acc3 (from task21), buf_t3tot2 (from task23), bb_t3t2 (from task23)
 * Writes: buf_order (to task21), buf_t2tot3 (to task23), bb_t2t3 (to task23)
 */
void* task22_job(void);

/* Periodic task: task23 (Tsk23)
 * Period=100ms  Priority=4  Stack=8KB
 * Reads:  buf_t2tot3 (from task22), bb_t2t3 (from task22)
 * Writes: buf_t3tot2 (to task22), bb_t3t2 (to task22), pr2queueingout (queuing SOURCE)
 */
void* task23_job(void);

#endif
