#include "globals.h"
/*****************************************************/
/*  This file was automatically generated by IMA2C  */
/*  Partition: ps2 (P2)  Module: M1                 */
/*****************************************************/
