#ifndef __IMA2C_GENERATED_GTYPES_H__
#define __IMA2C_GENERATED_GTYPES_H__

/*****************************************************/
/*  This file was automatically generated by IMA2C  */
/*  Partition: ps2 (P2)  Module: M1                 */
/*****************************************************/

#include <os/pos/apex/apexLib.h>

typedef int integer;

#endif
