#include "subprograms.h"
/*****************************************************/
/*  This file was automatically generated by IMA2C  */
/*  Partition: ps2 (P2)  Module: M1                 */
/*  User shall fill in the function bodies below.   */
/*****************************************************/

void commandboard_receiveinput_spg(integer *data_in, integer *data_out)
{
    /* TODO: user-defined receive logic */
    if (data_out != 0)
        *data_out = *data_in;
}

void commandboard_printinfos_spg(integer *data_in)
{
    /* TODO: user-defined print logic */
    (void)data_in;
}
