#ifndef __IMA2C_GENERATED_SUBPROGRAMS_H_
#define __IMA2C_GENERATED_SUBPROGRAMS_H_

/*****************************************************/
/*  This file was automatically generated by IMA2C  */
/*  Partition: ps2 (P2)  Module: M1                 */
/*****************************************************/

#include "gtypes.h"

/* Subprogram: commandboard_receiveinput_spg (called by task21, task23) */
void commandboard_receiveinput_spg(integer *data_in, integer *data_out);

/* Subprogram: commandboard_printinfos_spg (called by task21, task23) */
void commandboard_printinfos_spg(integer *data_in);

#endif
