#ifndef __PB_GENERATED_ACTIVITY_H_
#define __PB_GENERATED_ACTIVITY_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: pb  AADL: PB.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

/* Periodic task: taskB1 (AADL: TskB1)
 * Period=25ms  Priority=2  Stack=8192B */
void* taskB1_job(void);

/* Periodic task: taskB2 (AADL: TskB2)
 * Period=50ms  Priority=3  Stack=8192B */
void* taskB2_job(void);

#endif
