#include <os/pos/apex/apexLib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: pb  AADL: PB.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


#define SZ 1024

/* ================================================================== */
/*  taskB1  (AADL: TskB1)
 *  Period=25ms  Priority=2  Dispatch_Abs=0ms
 *  Inter-partition WRITES: sensor_out (SAMPLING SOURCE)
 *  Intra-partition WRITES (BB):  bb_data_link
 * ================================================================== */
extern BLACKBOARD_ID_TYPE pb_bb_data_link_id;
extern SAMPLING_PORT_ID_TYPE pb_sensor_out_id;

void* taskB1_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* WRITE inter-partition SAMPLING: sensor_out */
        WRITE_SAMPLING_MESSAGE(pb_sensor_out_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer), &ret);
        CHECK_CODE("WRITE_SAMPLING_MESSAGE(sensor_out)", ret);

        /* DISPLAY intra-partition BLACKBOARD: bb_data_link */
        DISPLAY_BLACKBOARD(pb_bb_data_link_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer), &ret);
        CHECK_CODE("DISPLAY_BLACKBOARD(bb_data_link)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(taskB1)", ret);
    }
}

/* ================================================================== */
/*  taskB2  (AADL: TskB2)
 *  Period=50ms  Priority=3  Dispatch_Abs=0ms
 *  Inter-partition WRITES: sensor_out (SAMPLING SOURCE)
 *  Inter-partition READS:  cmd_in (QUEUING DEST)
 *  Intra-partition READS  (BB):  bb_data_link
 * ================================================================== */
extern BLACKBOARD_ID_TYPE pb_bb_data_link_id;
extern QUEUING_PORT_ID_TYPE pb_cmd_in_id;
extern SAMPLING_PORT_ID_TYPE pb_sensor_out_id;

void* taskB2_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* RECEIVE inter-partition QUEUING: cmd_in */
        RECEIVE_QUEUING_MESSAGE(pb_cmd_in_id,
            5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(cmd_in)", ret);

        /* READ intra-partition BLACKBOARD: bb_data_link */
        READ_BLACKBOARD(pb_bb_data_link_id, 0ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("READ_BLACKBOARD(bb_data_link)", ret);

        /* WRITE inter-partition SAMPLING: sensor_out */
        WRITE_SAMPLING_MESSAGE(pb_sensor_out_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer), &ret);
        CHECK_CODE("WRITE_SAMPLING_MESSAGE(sensor_out)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(taskB2)", ret);
    }
}

