#ifndef __PB_GENERATED_SUBPROGRAMS_H_
#define __PB_GENERATED_SUBPROGRAMS_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: pb  AADL: PB.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

#include "gtypes.h"


#endif
