#include "subprograms.h"
/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: pb  AADL: PB.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

/* User shall fill in the function bodies. */

