#ifndef __PA_GENERATED_ACTIVITY_H_
#define __PA_GENERATED_ACTIVITY_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: pa  AADL: PA.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

/* Periodic task: taskA1 (AADL: TskA1)
 * Period=50ms  Priority=2  Stack=8192B */
void* taskA1_job(void);

#endif
