#include <os/pos/apex/apexLib.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: pa  AADL: PA.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


PROCESS_ID_TYPE arinc_threads[ACoreOS653_CONFIG_NB_THREADS];

/* ---- Inter-partition ports ---- */
QUEUING_PORT_ID_TYPE  pa_ctrl_in_id;

void appMain(void)
{
    PROCESS_ATTRIBUTE_TYPE tattr;
    RETURN_CODE_TYPE ret = NO_ERROR;

    /* 1. Task: taskA1 (AADL: TskA1)  Period=50ms Priority=2 */
    strcpy(tattr.NAME, "taskA1");
    tattr.ENTRY_POINT   = taskA1_job;
    tattr.BASE_PRIORITY = 2;
    tattr.PERIOD        = 50000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 50000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[0]), &ret);
    CHECK_CODE("CREATE_PROCESS(taskA1)", ret);
    START(arinc_threads[0], &ret);
    CHECK_CODE("START(taskA1)", ret);

    /* 2. Queuing port: ctrl_in (DESTINATION) */
    CREATE_QUEUING_PORT(
        "ctrl_in",
        sizeof(integer),
        4,
        DESTINATION,
        FIFO,
        &(pa_ctrl_in_id), &ret);
    CHECK_CODE("CREATE_QUEUING_PORT(ctrl_in)", ret);

    /* 3. Switch to NORMAL operating mode */
    SET_PARTITION_MODE(NORMAL, &ret);
    CHECK_CODE("SET_PARTITION_MODE(NORMAL)", ret);
    return;
}
