#include <os/pos/apex/apexLib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: nav  AADL: NAV.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


#define SZ 1024

/* ================================================================== */
/*  taskN1  (AADL: TskN1)
 *  Period=25ms  Priority=2  Dispatch_Abs=0ms
 *  Inter-partition WRITES: pos_out, status_out (SAMPLING SOURCE)
 *  Intra-partition WRITES (BB):  bb_bb1, bb_bb2
 * ================================================================== */
extern BLACKBOARD_ID_TYPE nav_bb_bb1_id;
extern BLACKBOARD_ID_TYPE nav_bb_bb2_id;
extern SAMPLING_PORT_ID_TYPE nav_pos_out_id;
extern SAMPLING_PORT_ID_TYPE nav_status_out_id;

void* taskN1_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* WRITE inter-partition SAMPLING: pos_out */
        WRITE_SAMPLING_MESSAGE(nav_pos_out_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer), &ret);
        CHECK_CODE("WRITE_SAMPLING_MESSAGE(pos_out)", ret);

        /* WRITE inter-partition SAMPLING: status_out */
        WRITE_SAMPLING_MESSAGE(nav_status_out_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer), &ret);
        CHECK_CODE("WRITE_SAMPLING_MESSAGE(status_out)", ret);

        /* DISPLAY intra-partition BLACKBOARD: bb_bb1 */
        DISPLAY_BLACKBOARD(nav_bb_bb1_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer), &ret);
        CHECK_CODE("DISPLAY_BLACKBOARD(bb_bb1)", ret);

        /* DISPLAY intra-partition BLACKBOARD: bb_bb2 */
        DISPLAY_BLACKBOARD(nav_bb_bb2_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer), &ret);
        CHECK_CODE("DISPLAY_BLACKBOARD(bb_bb2)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(taskN1)", ret);
    }
}

/* ================================================================== */
/*  taskN2  (AADL: TskN2)
 *  Period=50ms  Priority=3  Dispatch_Abs=0ms
 *  Inter-partition WRITES: pos_out, status_out (SAMPLING SOURCE)
 *  Intra-partition READS  (BB):  bb_bb1
 *  Intra-partition WRITES (BUF): buf_buf1
 * ================================================================== */
extern BLACKBOARD_ID_TYPE nav_bb_bb1_id;
extern BUFFER_ID_TYPE nav_buf_buf1_id;
extern SAMPLING_PORT_ID_TYPE nav_pos_out_id;
extern SAMPLING_PORT_ID_TYPE nav_status_out_id;

void* taskN2_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* READ intra-partition BLACKBOARD: bb_bb1 */
        READ_BLACKBOARD(nav_bb_bb1_id, 0ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("READ_BLACKBOARD(bb_bb1)", ret);

        /* WRITE inter-partition SAMPLING: pos_out */
        WRITE_SAMPLING_MESSAGE(nav_pos_out_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer), &ret);
        CHECK_CODE("WRITE_SAMPLING_MESSAGE(pos_out)", ret);

        /* WRITE inter-partition SAMPLING: status_out */
        WRITE_SAMPLING_MESSAGE(nav_status_out_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer), &ret);
        CHECK_CODE("WRITE_SAMPLING_MESSAGE(status_out)", ret);

        /* WRITE intra-partition BUFFER: buf_buf1 */
        WRITE_BUFFER(nav_buf_buf1_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer),
            5000000ll, &ret);
        CHECK_CODE("WRITE_BUFFER(buf_buf1)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(taskN2)", ret);
    }
}

/* ================================================================== */
/*  taskN3  (AADL: TskN3)
 *  Period=100ms  Priority=4  Dispatch_Abs=0ms
 *  Inter-partition WRITES: pos_out, status_out (SAMPLING SOURCE)
 *  Intra-partition READS  (BB):  bb_bb2
 * ================================================================== */
extern BLACKBOARD_ID_TYPE nav_bb_bb2_id;
extern SAMPLING_PORT_ID_TYPE nav_pos_out_id;
extern SAMPLING_PORT_ID_TYPE nav_status_out_id;

void* taskN3_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* READ intra-partition BLACKBOARD: bb_bb2 */
        READ_BLACKBOARD(nav_bb_bb2_id, 0ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("READ_BLACKBOARD(bb_bb2)", ret);

        /* WRITE inter-partition SAMPLING: pos_out */
        WRITE_SAMPLING_MESSAGE(nav_pos_out_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer), &ret);
        CHECK_CODE("WRITE_SAMPLING_MESSAGE(pos_out)", ret);

        /* WRITE inter-partition SAMPLING: status_out */
        WRITE_SAMPLING_MESSAGE(nav_status_out_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer), &ret);
        CHECK_CODE("WRITE_SAMPLING_MESSAGE(status_out)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(taskN3)", ret);
    }
}

/* ================================================================== */
/*  taskN4  (AADL: TskN4)
 *  Period=50ms  Priority=5  Dispatch_Abs=0ms
 *  Inter-partition WRITES: cmd_out (QUEUING SOURCE)
 *  Intra-partition READS  (BUF): buf_buf1
 * ================================================================== */
extern BUFFER_ID_TYPE nav_buf_buf1_id;
extern QUEUING_PORT_ID_TYPE nav_cmd_out_id;

void* taskN4_job(void)
{
    RETURN_CODE_TYPE ret = NO_ERROR;
    MESSAGE_SIZE_TYPE msg_len;
    integer val = 0;

    while (1)
    {
        /* READ intra-partition BUFFER: buf_buf1 */
        READ_BUFFER(nav_buf_buf1_id, 5000000ll,
            (MESSAGE_ADDR_TYPE)&val, &msg_len, &ret);
        CHECK_CODE("READ_BUFFER(buf_buf1)", ret);

        /* SEND inter-partition QUEUING: cmd_out */
        SEND_QUEUING_MESSAGE(nav_cmd_out_id,
            (MESSAGE_ADDR_TYPE)&val, sizeof(integer),
            5000000ll, &ret);
        CHECK_CODE("SEND_QUEUING_MESSAGE(cmd_out)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(taskN4)", ret);
    }
}

