#ifndef __NAV_GENERATED_ACTIVITY_H_
#define __NAV_GENERATED_ACTIVITY_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: nav  AADL: NAV.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

/* Periodic task: taskN1 (AADL: TskN1)
 * Period=25ms  Priority=2  Stack=8192B */
void* taskN1_job(void);

/* Periodic task: taskN2 (AADL: TskN2)
 * Period=50ms  Priority=3  Stack=8192B */
void* taskN2_job(void);

/* Periodic task: taskN3 (AADL: TskN3)
 * Period=100ms  Priority=4  Stack=8192B */
void* taskN3_job(void);

/* Periodic task: taskN4 (AADL: TskN4)
 * Period=50ms  Priority=5  Stack=8192B */
void* taskN4_job(void);

#endif
