#include <os/pos/apex/apexLib.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: nav  AADL: NAV.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/


PROCESS_ID_TYPE arinc_threads[ACoreOS653_CONFIG_NB_THREADS];

/* ---- Inter-partition ports ---- */
SAMPLING_PORT_ID_TYPE nav_pos_out_id;
SAMPLING_PORT_ID_TYPE nav_status_out_id;
QUEUING_PORT_ID_TYPE  nav_cmd_out_id;

/* ---- Intra-partition blackboards ---- */
BLACKBOARD_ID_TYPE nav_bb_bb1_id;  /* taskN1 -> taskN2 */
BLACKBOARD_ID_TYPE nav_bb_bb2_id;  /* taskN1 -> taskN3 */

/* ---- Intra-partition buffers ---- */
BUFFER_ID_TYPE nav_buf_buf1_id;  /* taskN2 -> taskN4 */

void appMain(void)
{
    PROCESS_ATTRIBUTE_TYPE tattr;
    RETURN_CODE_TYPE ret = NO_ERROR;

    /* 1. Sampling port: pos_out (SOURCE) */
    CREATE_SAMPLING_PORT(
        "pos_out",
        sizeof(integer),
        SOURCE,
        100000000ll,
        &(nav_pos_out_id), &ret);
    CHECK_CODE("CREATE_SAMPLING_PORT(pos_out)", ret);

    /* 2. Sampling port: status_out (SOURCE) */
    CREATE_SAMPLING_PORT(
        "status_out",
        sizeof(integer),
        SOURCE,
        100000000ll,
        &(nav_status_out_id), &ret);
    CHECK_CODE("CREATE_SAMPLING_PORT(status_out)", ret);

    /* 3. Blackboard: bb_bb1  (taskN1 -> taskN2) */
    CREATE_BLACKBOARD(
        "bb_bb1",
        sizeof(integer),
        &(nav_bb_bb1_id), &ret);
    CHECK_CODE("CREATE_BLACKBOARD(bb_bb1)", ret);

    /* 4. Blackboard: bb_bb2  (taskN1 -> taskN3) */
    CREATE_BLACKBOARD(
        "bb_bb2",
        sizeof(integer),
        &(nav_bb_bb2_id), &ret);
    CHECK_CODE("CREATE_BLACKBOARD(bb_bb2)", ret);

    /* 5. Buffer: buf_buf1  (taskN2 -> taskN4) */
    CREATE_BUFFER(
        "buf_buf1",
        sizeof(integer),
        4,
        FIFO,
        &(nav_buf_buf1_id), &ret);
    CHECK_CODE("CREATE_BUFFER(buf_buf1)", ret);

    /* 6. Task: taskN1 (AADL: TskN1)  Period=25ms Priority=2 */
    strcpy(tattr.NAME, "taskN1");
    tattr.ENTRY_POINT   = taskN1_job;
    tattr.BASE_PRIORITY = 2;
    tattr.PERIOD        = 25000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 25000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[0]), &ret);
    CHECK_CODE("CREATE_PROCESS(taskN1)", ret);
    START(arinc_threads[0], &ret);
    CHECK_CODE("START(taskN1)", ret);

    /* 7. Task: taskN2 (AADL: TskN2)  Period=50ms Priority=3 */
    strcpy(tattr.NAME, "taskN2");
    tattr.ENTRY_POINT   = taskN2_job;
    tattr.BASE_PRIORITY = 3;
    tattr.PERIOD        = 50000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 50000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[1]), &ret);
    CHECK_CODE("CREATE_PROCESS(taskN2)", ret);
    START(arinc_threads[1], &ret);
    CHECK_CODE("START(taskN2)", ret);

    /* 8. Task: taskN3 (AADL: TskN3)  Period=100ms Priority=4 */
    strcpy(tattr.NAME, "taskN3");
    tattr.ENTRY_POINT   = taskN3_job;
    tattr.BASE_PRIORITY = 4;
    tattr.PERIOD        = 100000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 100000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[2]), &ret);
    CHECK_CODE("CREATE_PROCESS(taskN3)", ret);
    START(arinc_threads[2], &ret);
    CHECK_CODE("START(taskN3)", ret);

    /* 9. Task: taskN4 (AADL: TskN4)  Period=50ms Priority=5 */
    strcpy(tattr.NAME, "taskN4");
    tattr.ENTRY_POINT   = taskN4_job;
    tattr.BASE_PRIORITY = 5;
    tattr.PERIOD        = 50000000ll;
    tattr.STACK_SIZE    = 8192;
    tattr.TIME_CAPACITY = 50000000ll;
    tattr.DEADLINE      = SOFT;
    CREATE_PROCESS(&(tattr), &(arinc_threads[3]), &ret);
    CHECK_CODE("CREATE_PROCESS(taskN4)", ret);
    START(arinc_threads[3], &ret);
    CHECK_CODE("START(taskN4)", ret);

    /* 10. Queuing port: cmd_out (SOURCE) */
    CREATE_QUEUING_PORT(
        "cmd_out",
        sizeof(integer),
        4,
        SOURCE,
        FIFO,
        &(nav_cmd_out_id), &ret);
    CHECK_CODE("CREATE_QUEUING_PORT(cmd_out)", ret);

    /* 11. Switch to NORMAL operating mode */
    SET_PARTITION_MODE(NORMAL, &ret);
    CHECK_CODE("SET_PARTITION_MODE(NORMAL)", ret);
    return;
}
