#ifndef __NAV_GENERATED_SUBPROGRAMS_H_
#define __NAV_GENERATED_SUBPROGRAMS_H_

/*****************************************************/
/*  This file was automatically generated by aadl2c */
/*  Partition: nav  AADL: NAV.impl              */
/*  DO NOT hand-modify: changes will be overwritten  */
/*****************************************************/

#include "gtypes.h"


#endif
