#ifndef __IMA2C_GENERATED_ACTIVITY_H_
#define __IMA2C_GENERATED_ACTIVITY_H_

/*****************************************************/
/*  This file was automatically generated by IMA2C  */
/*  Partition: ps1 (P1)  Module: M1                 */
/*****************************************************/

/* Periodic task: task11 (Tsk11)
 * Period=25ms  Priority=2  Stack=8KB
 * Writes: pr1samplingout (sampling SOURCE), bb_acc1, bb_acc2
 * Reads:  buf_sensor (from task12)
 */
void* task11_job(void);

/* Periodic task: task12 (Tsk12)
 * Period=50ms  Priority=3  Stack=8KB
 * Reads:  bb_acc1, bb_acc2 (from task11)
 * Writes: buf_sensor (to task11), bb_sem (to task13, protected access)
 */
void* task12_job(void);

/* Periodic task: task13 (Tsk13)
 * Period=50ms  Priority=4  Stack=8KB
 * Reads:  bb_sem (from task12, protected), buf_t4tot3 (from task14), bb_t4t3 (from task14)
 * Writes: buf_t3tot4 (to task14), bb_t3t4 (to task14)
 */
void* task13_job(void);

/* Periodic task: task14 (Tsk14)
 * Period=50ms  Priority=5  Stack=8KB
 * Reads:  pr1queueingin (queuing DESTINATION), buf_t3tot4 (from task13), bb_t3t4 (from task13)
 * Writes: buf_t4tot3 (to task13), bb_t4t3 (to task13)
 */
void* task14_job(void);

#endif
