#include <os/pos/apex/apexLib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "activity.h"
#include "gtypes.h"
#include "deployment.h"
#include "globals.h"
#include "subprograms.h"

/*****************************************************/
/*  Partition: ps1 (P1)  Module: M1                 */
/*  Task activity bodies - generated by IMA2C       */
/*****************************************************/

#define SZ 1024   /* safe message buffer size */

/* ================================================================== */
/*  task11  (AADL: Tsk11)                                             */
/*  Period=25ms  Priority=2  Dispatch_Absolute_Time=2ms               */
/*  Inter-partition WRITES: pr1samplingout (SAMPLING SOURCE)          */
/*  Intra-partition WRITES: bb_acc1, bb_acc2   (to task12)            */
/*  Intra-partition READS:  buf_sensor         (from task12)          */
/* ================================================================== */
extern SAMPLING_PORT_ID_TYPE ps1_pr1samplingout_id;
extern BLACKBOARD_ID_TYPE    ps1_bb_acc1_id;
extern BLACKBOARD_ID_TYPE    ps1_bb_acc2_id;
extern BUFFER_ID_TYPE        ps1_buf_sensor_id;

void* task11_job(void)
{
    RETURN_CODE_TYPE    ret = NO_ERROR;
    MESSAGE_SIZE_TYPE   buf_sensor_len;

    /* Outgoing data values */
    integer ps1_pr1samplingout_val  = 0;
    integer ps1_bb_acc1_val         = 0;
    integer ps1_bb_acc2_val         = 0;
    /* Incoming data value */
    integer ps1_buf_sensor_val      = 0;

    while (1)
    {
        /* ---- READ from intra-partition BUFFER buf_sensor (task12 writes) ---- */
        READ_BUFFER(ps1_buf_sensor_id,
                    0ll,                                 /* TIME_OUT: poll (no block) */
                    (MESSAGE_ADDR_TYPE)&ps1_buf_sensor_val,
                    &buf_sensor_len,
                    &ret);
        CHECK_CODE("READ_BUFFER(buf_sensor)", ret);

        /* ---- Call user subprogram: commandboard_receiveinput_spg ---- */
        commandboard_receiveinput_spg(&ps1_buf_sensor_val, &ps1_pr1samplingout_val);

        /* ---- Call user subprogram: commandboard_printinfos_spg ---- */
        commandboard_printinfos_spg(&ps1_pr1samplingout_val);

        /* ---- WRITE to intra-partition BLACKBOARD bb_acc1 (task12 reads) ---- */
        DISPLAY_BLACKBOARD(ps1_bb_acc1_id,
                           (MESSAGE_ADDR_TYPE)&ps1_bb_acc1_val,
                           sizeof(integer),
                           &ret);
        CHECK_CODE("DISPLAY_BLACKBOARD(bb_acc1)", ret);

        /* ---- WRITE to intra-partition BLACKBOARD bb_acc2 (task12 reads) ---- */
        DISPLAY_BLACKBOARD(ps1_bb_acc2_id,
                           (MESSAGE_ADDR_TYPE)&ps1_bb_acc2_val,
                           sizeof(integer),
                           &ret);
        CHECK_CODE("DISPLAY_BLACKBOARD(bb_acc2)", ret);

        /* ---- WRITE to inter-partition SAMPLING port pr1samplingout ---- */
        WRITE_SAMPLING_MESSAGE(ps1_pr1samplingout_id,
                               (MESSAGE_ADDR_TYPE)&ps1_pr1samplingout_val,
                               sizeof(integer),
                               &ret);
        CHECK_CODE("WRITE_SAMPLING_MESSAGE(pr1samplingout)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task11)", ret);
    }
}

/* ================================================================== */
/*  task12  (AADL: Tsk12)                                             */
/*  Period=50ms  Priority=3  Dispatch_Absolute_Time=3ms               */
/*  Intra-partition READS:  bb_acc1, bb_acc2   (from task11)          */
/*  Intra-partition WRITES: buf_sensor         (to task11)            */
/*                          bb_sem             (to task13, protected) */
/* ================================================================== */
extern BLACKBOARD_ID_TYPE ps1_bb_sem_id;
extern BUFFER_ID_TYPE     ps1_buf_sensor_id;   /* re-used extern, already declared */

void* task12_job(void)
{
    RETURN_CODE_TYPE    ret = NO_ERROR;
    MESSAGE_SIZE_TYPE   bb_acc1_len, bb_acc2_len;

    integer ps1_bb_acc1_val  = 0;
    integer ps1_bb_acc2_val  = 0;
    integer ps1_buf_sensor_val = 0;   /* feedback to task11 */
    integer ps1_bb_sem_val   = 0;    /* protected data written to task13 */

    while (1)
    {
        /* ---- READ from intra-partition BLACKBOARD bb_acc1 (task11 writes) ---- */
        READ_BLACKBOARD(ps1_bb_acc1_id,
                        0ll,                              /* TIME_OUT: poll */
                        (MESSAGE_ADDR_TYPE)&ps1_bb_acc1_val,
                        &bb_acc1_len,
                        &ret);
        CHECK_CODE("READ_BLACKBOARD(bb_acc1)", ret);

        /* ---- READ from intra-partition BLACKBOARD bb_acc2 (task11 writes) ---- */
        READ_BLACKBOARD(ps1_bb_acc2_id,
                        0ll,
                        (MESSAGE_ADDR_TYPE)&ps1_bb_acc2_val,
                        &bb_acc2_len,
                        &ret);
        CHECK_CODE("READ_BLACKBOARD(bb_acc2)", ret);

        /* ---- User computation using acc data ---- */
        ps1_buf_sensor_val = ps1_bb_acc1_val + ps1_bb_acc2_val;  /* placeholder */
        ps1_bb_sem_val     = ps1_bb_acc1_val;

        /* ---- WRITE to intra-partition BUFFER buf_sensor (task11 reads) ---- */
        WRITE_BUFFER(ps1_buf_sensor_id,
                     (MESSAGE_ADDR_TYPE)&ps1_buf_sensor_val,
                     sizeof(integer),
                     0ll,                              /* TIME_OUT: poll */
                     &ret);
        CHECK_CODE("WRITE_BUFFER(buf_sensor)", ret);

        /* ---- WRITE to intra-partition BLACKBOARD bb_sem (task13 reads)  ----
         *  bb_sem maps to AADL protected_data 'sem'.
         *  task12 has write_only access (task2_printer), implemented as
         *  DISPLAY_BLACKBOARD - ARINC 653 guarantees atomic update.           */
        DISPLAY_BLACKBOARD(ps1_bb_sem_id,
                           (MESSAGE_ADDR_TYPE)&ps1_bb_sem_val,
                           sizeof(integer),
                           &ret);
        CHECK_CODE("DISPLAY_BLACKBOARD(bb_sem)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task12)", ret);
    }
}

/* ================================================================== */
/*  task13  (AADL: Tsk13)                                             */
/*  Period=50ms  Priority=4  Dispatch_Absolute_Time=3ms               */
/*  Intra-partition READS:  bb_sem   (from task12, protected)         */
/*                          buf_t4tot3, bb_t4t3  (from task14)        */
/*  Intra-partition WRITES: buf_t3tot4, bb_t3t4  (to task14)          */
/* ================================================================== */
extern BLACKBOARD_ID_TYPE ps1_bb_t3t4_id;
extern BLACKBOARD_ID_TYPE ps1_bb_t4t3_id;
extern BUFFER_ID_TYPE     ps1_buf_t3tot4_id;
extern BUFFER_ID_TYPE     ps1_buf_t4tot3_id;

void* task13_job(void)
{
    RETURN_CODE_TYPE    ret = NO_ERROR;
    MESSAGE_SIZE_TYPE   bb_sem_len, bb_t4t3_len, buf_t4tot3_len;

    integer ps1_bb_sem_val     = 0;
    integer ps1_buf_t4tot3_val = 0;
    integer ps1_bb_t4t3_val    = 0;
    integer ps1_buf_t3tot4_val = 0;   /* send to task14 via buffer */
    integer ps1_bb_t3t4_val    = 0;   /* send to task14 via blackboard */

    while (1)
    {
        /* ---- READ from intra-partition BLACKBOARD bb_sem (task12 writes, protected) ----
         *  task13 has read_only access (task3_receiver) to protected_data.
         *  READ_BLACKBOARD retrieves the last value written by task12.        */
        READ_BLACKBOARD(ps1_bb_sem_id,
                        0ll,
                        (MESSAGE_ADDR_TYPE)&ps1_bb_sem_val,
                        &bb_sem_len,
                        &ret);
        CHECK_CODE("READ_BLACKBOARD(bb_sem)", ret);

        /* ---- Call user subprogram: commandboard_receiveinput_spg ---- */
        commandboard_receiveinput_spg(&ps1_bb_sem_val, &ps1_buf_t3tot4_val);

        /* ---- READ from intra-partition BUFFER buf_t4tot3 (task14 writes) ---- */
        READ_BUFFER(ps1_buf_t4tot3_id,
                    5000000ll,                        /* TIME_OUT: 5 ms */
                    (MESSAGE_ADDR_TYPE)&ps1_buf_t4tot3_val,
                    &buf_t4tot3_len,
                    &ret);
        CHECK_CODE("READ_BUFFER(buf_t4tot3)", ret);

        /* ---- READ from intra-partition BLACKBOARD bb_t4t3 (task14 writes) ---- */
        READ_BLACKBOARD(ps1_bb_t4t3_id,
                        0ll,
                        (MESSAGE_ADDR_TYPE)&ps1_bb_t4t3_val,
                        &bb_t4t3_len,
                        &ret);
        CHECK_CODE("READ_BLACKBOARD(bb_t4t3)", ret);

        /* ---- User computation ---- */
        ps1_bb_t3t4_val = ps1_buf_t4tot3_val + ps1_bb_t4t3_val;  /* placeholder */

        /* ---- WRITE to intra-partition BUFFER buf_t3tot4 (task14 reads) ---- */
        WRITE_BUFFER(ps1_buf_t3tot4_id,
                     (MESSAGE_ADDR_TYPE)&ps1_buf_t3tot4_val,
                     sizeof(integer),
                     5000000ll,                       /* TIME_OUT: 5 ms */
                     &ret);
        CHECK_CODE("WRITE_BUFFER(buf_t3tot4)", ret);

        /* ---- WRITE to intra-partition BLACKBOARD bb_t3t4 (task14 reads) ---- */
        DISPLAY_BLACKBOARD(ps1_bb_t3t4_id,
                           (MESSAGE_ADDR_TYPE)&ps1_bb_t3t4_val,
                           sizeof(integer),
                           &ret);
        CHECK_CODE("DISPLAY_BLACKBOARD(bb_t3t4)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task13)", ret);
    }
}

/* ================================================================== */
/*  task14  (AADL: Tsk14)                                             */
/*  Period=50ms  Priority=5  Dispatch_Absolute_Time=0ms               */
/*  Inter-partition READS:  pr1queueingin (QUEUING DESTINATION)       */
/*  Intra-partition READS:  buf_t3tot4, bb_t3t4  (from task13)        */
/*  Intra-partition WRITES: buf_t4tot3, bb_t4t3  (to task13)          */
/*  Subprogram call: calculate_spg (bb_t3t4 -> bb_t4t3)              */
/* ================================================================== */
extern QUEUING_PORT_ID_TYPE ps1_pr1queueingin_id;

void* task14_job(void)
{
    RETURN_CODE_TYPE    ret = NO_ERROR;
    MESSAGE_SIZE_TYPE   qin_len, buf_t3tot4_len, bb_t3t4_len;

    integer ps1_pr1queueingin_val = 0;
    integer ps1_buf_t3tot4_val    = 0;
    integer ps1_bb_t3t4_val       = 0;   /* calculate_spg input */
    integer ps1_buf_t4tot3_val    = 0;
    integer ps1_bb_t4t3_val       = 0;   /* calculate_spg output */

    while (1)
    {
        /* ---- RECEIVE from inter-partition QUEUING port pr1queueingin ---- */
        RECEIVE_QUEUING_MESSAGE(ps1_pr1queueingin_id,
                                5000000ll,             /* TIME_OUT: 5 ms (from AADL Timeout=5ns) */
                                (MESSAGE_ADDR_TYPE)&ps1_pr1queueingin_val,
                                &qin_len,
                                &ret);
        CHECK_CODE("RECEIVE_QUEUING_MESSAGE(pr1queueingin)", ret);

        /* ---- READ from intra-partition BUFFER buf_t3tot4 (task13 writes) ---- */
        READ_BUFFER(ps1_buf_t3tot4_id,
                    5000000ll,
                    (MESSAGE_ADDR_TYPE)&ps1_buf_t3tot4_val,
                    &buf_t3tot4_len,
                    &ret);
        CHECK_CODE("READ_BUFFER(buf_t3tot4)", ret);

        /* ---- READ from intra-partition BLACKBOARD bb_t3t4 (task13 writes) ---- */
        READ_BLACKBOARD(ps1_bb_t3t4_id,
                        0ll,
                        (MESSAGE_ADDR_TYPE)&ps1_bb_t3t4_val,
                        &bb_t3t4_len,
                        &ret);
        CHECK_CODE("READ_BLACKBOARD(bb_t3t4)", ret);

        /* ---- Call user subprogram: calculate_spg ----
         *  AADL: C1: parameter task4_blackboard_read -> calculate_spg.data_in
         *        C2: parameter calculate_spg.data_out -> task4_blackboard_write */
        calculate_spg(&ps1_bb_t3t4_val, &ps1_bb_t4t3_val);

        /* ---- WRITE to intra-partition BUFFER buf_t4tot3 (task13 reads) ---- */
        ps1_buf_t4tot3_val = ps1_buf_t3tot4_val + ps1_pr1queueingin_val; /* placeholder */
        WRITE_BUFFER(ps1_buf_t4tot3_id,
                     (MESSAGE_ADDR_TYPE)&ps1_buf_t4tot3_val,
                     sizeof(integer),
                     5000000ll,
                     &ret);
        CHECK_CODE("WRITE_BUFFER(buf_t4tot3)", ret);

        /* ---- WRITE to intra-partition BLACKBOARD bb_t4t3 (task13 reads) ---- */
        DISPLAY_BLACKBOARD(ps1_bb_t4t3_id,
                           (MESSAGE_ADDR_TYPE)&ps1_bb_t4t3_val,
                           sizeof(integer),
                           &ret);
        CHECK_CODE("DISPLAY_BLACKBOARD(bb_t4t3)", ret);

        PERIODIC_WAIT(&ret);
        CHECK_CODE("PERIODIC_WAIT(task14)", ret);
    }
}
