#ifndef __IMA2C_GENERATED_DEPLOYMENT_H_
#define __IMA2C_GENERATED_DEPLOYMENT_H_

/*****************************************************/
/*  This file was automatically generated by IMA2C  */
/*  Partition: ps1 (P1)  Module: M1 (arinckernel.module1) */
/*****************************************************/

#define IMA2C_RUNTIME_ACoreOS653 1

#define ACoreOS653_GENERATED_CODE 1

/* Number of tasks (threads) in this partition */
#define ACoreOS653_CONFIG_NB_THREADS 4      /* task11, task12, task13, task14 */

/* Number of inter-partition communication ports */
#define ACoreOS653_CONFIG_NB_SAMPLINGS 1    /* pr1samplingout (SOURCE) */
#define ACoreOS653_CONFIG_NB_QUEUEINGS 1    /* pr1queueingin  (DESTINATION) */

/* Number of intra-partition communication resources */
#define ACoreOS653_CONFIG_NB_BLACKBOARDS 5  /* bb_acc1, bb_acc2, bb_sem, bb_t3t4, bb_t4t3 */
#define ACoreOS653_CONFIG_NB_BUFFERS 3      /* buf_sensor, buf_t3tot4, buf_t4tot3 */

/* Required ARINC 653 services */
#define ACoreOS653_NEEDS_ARINC653_PARTITION  1
#define ACoreOS653_NEEDS_ARINC653_PROCESS    1
#define ACoreOS653_NEEDS_ARINC653_SAMPLING   1
#define ACoreOS653_NEEDS_ARINC653_QUEUEING   1
#define ACoreOS653_NEEDS_ARINC653_BLACKBOARD 1
#define ACoreOS653_NEEDS_ARINC653_BUFFER     1
#define ACoreOS653_NEEDS_ARINC653_SEMAPHORE  0
#define ACoreOS653_NEEDS_ARINC653_EVENT      0
#define ACoreOS653_NEEDS_MIDDLEWARE          1
#define ACoreOS653_NEEDS_ARINC653_TIME       1

/* Total stack space: 4 tasks x 8192 bytes */
#define ACoreOS653_CONFIG_STACKS_SIZE 32768

#endif
