#ifndef __IMA2C_GENERATED_GTYPES_H__
#define __IMA2C_GENERATED_GTYPES_H__

/*****************************************************/
/*  This file was automatically generated by IMA2C  */
/*  Partition: ps1 (P1)  Module: M1                 */
/*****************************************************/

#include <os/pos/apex/apexLib.h>

/* Base data type used for inter/intra-partition messages */
typedef int integer;

#endif
