#include "gtypes.h"
/*****************************************************/
/*  This file was automatically generated by IMA2C  */
/*  Partition: ps1 (P1)  Module: M1                 */
/*****************************************************/
