#ifndef __IMA2C_GENERATED_SUBPROGRAMS_H_
#define __IMA2C_GENERATED_SUBPROGRAMS_H_

/*****************************************************/
/*  This file was automatically generated by IMA2C  */
/*  Partition: ps1 (P1)  Module: M1                 */
/*****************************************************/

#include "gtypes.h"

/* Subprogram: commandboard_receiveinput_spg (called by task11, task13) */
void commandboard_receiveinput_spg(integer *data_in, integer *data_out);

/* Subprogram: commandboard_printinfos_spg (called by task11) */
void commandboard_printinfos_spg(integer *data_in);

/* Subprogram: calculate_spg (called by task14) */
void calculate_spg(integer *data_in, integer *data_out);

#endif
