#include "subprograms.h"
/*****************************************************/
/*  This file was automatically generated by IMA2C  */
/*  Partition: ps1 (P1)  Module: M1                 */
/*  User shall fill in the function bodies below.   */
/*****************************************************/

/* Subprogram: commandboard_receiveinput_spg
 * AADL source: subprograms::commandboard_receiveinput_spg
 * Called by: task11 (Tsk11), task13 (Tsk13)
 */
void commandboard_receiveinput_spg(integer *data_in, integer *data_out)
{
    /* TODO: user-defined receive logic */
    if (data_out != 0)
        *data_out = *data_in;
}

/* Subprogram: commandboard_printinfos_spg
 * AADL source: subprograms::commandboard_printinfos_spg
 * Called by: task11 (Tsk11)
 */
void commandboard_printinfos_spg(integer *data_in)
{
    /* TODO: user-defined print logic */
    (void)data_in;
}

/* Subprogram: calculate_spg
 * AADL source: subprograms::calculate_spg
 * Called by: task14 (Tsk14) - data_in: task4_blackboard_read, data_out: task4_blackboard_write
 */
void calculate_spg(integer *data_in, integer *data_out)
{
    /* TODO: user-defined calculation logic */
    if (data_out != 0)
        *data_out = *data_in;
}
