source.. = src/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               lib/commons-lang3-3.9.jar,\
               lib/antlr-4.1-complete.jar,\
               lib/ST-4.0.8.jar
